# Generated by Django 3.2 on 2022-11-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0002_alter_package_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(max_length=128)),
                ('command', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('output', models.CharField(max_length=200)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='package.package')),
            ],
        ),
    ]
