# Generated by Django 6.0.6 on 2026-06-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filemanager', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(max_length=128)),
                ('command', models.CharField(max_length=200)),
                ('original_file_name', models.CharField(max_length=128, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployment_actions', to='filemanager.filemanager')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_list', to='package.package')),
            ],
        ),
    ]
