# Generated by Django 3.2 on 2022-11-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='package_id',
            new_name='package',
        ),
    ]
