# Generated by Django 3.2 on 2022-11-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_id'),
        ('action', '0002_rename_package_id_action_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='package.package'),
        ),
    ]
