# Generated by Django 3.2 on 2022-11-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_alter_action_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='file',
        ),
    ]
