# Generated by Django 4.2.4 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_remove_action_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='action',
            name='output',
            field=models.TextField(),
        ),
    ]
