# Generated by Django 4.2.4 on 2023-08-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_action_file_alter_action_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='output',
        ),
    ]
