# Generated by Django 4.2.4 on 2023-09-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_package_target_os'),
        ('action', '0006_remove_action_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_list', to='package.package'),
        ),
    ]
