# Generated by Django 3.2 on 2021-10-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_network_group'),
        ('netdevice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netdevice',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netdevices', to='network.network'),
        ),
    ]
