# Generated by Django 4.2.4 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdevice', '0002_alter_netdevice_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='netdevice',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
