# Generated by Django 4.2.7 on 2025-04-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('section', '0002_alter_section_retrival_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sections', to='inventory_base.inventorybase')),
                ('template_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
            ],
        ),
    ]
