version = 1

exclude_patterns = [
    "**/migrations/**",
    "manage.py",
    "**/settings.py",
    "tools/",
]

[[analyzers]]
name = "python"
enabled = true
max_line_length = 128

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"
enabled = true

