# Generated by Django 4.2.4 on 2023-08-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.scheduler')),
            ],
        ),
    ]
