# Generated by Django 3.2.15 on 2023-03-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=255)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.scheduler')),
            ],
        ),
    ]
