# Generated by Django 6.0.1 on 2026-02-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("field", "0008_debian_linux"),
        ("section", "0008_debian_linux"),
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_major_version_mappings",
                        to="field.field",
                    ),
                ),
                (
                    "minor_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_minor_version_mappings",
                        to="field.field",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_name_mappings",
                        to="field.field",
                    ),
                ),
                (
                    "patch_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_patch_version_mappings",
                        to="field.field",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_publisher_mappings",
                        to="field.field",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_mappings",
                        to="section.section",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_mappings",
                        to="template.template",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software_version_mappings",
                        to="field.field",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftwareDictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("publisher", models.TextField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "major_version",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "minor_version",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "patch_version",
                    models.IntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="software_dictionary_entries",
                        to="inventory_base.inventorybase",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="software_so_name_0b22a7_idx"),
                    models.Index(
                        fields=["publisher"], name="software_so_publish_164935_idx"
                    ),
                    models.Index(
                        fields=["version"], name="software_so_version_e630b4_idx"
                    ),
                ],
            },
        ),
    ]
