# Generated by Django 6.0.6 on 2026-06-05 13:38

import uuid

import filemanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=filemanager.models.FileManager.upload_to
                    ),
                ),
                ("filesize", models.IntegerField()),
                ("mimetype", models.CharField(max_length=100)),
                ("linked_model", models.CharField(max_length=100)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
