# Generated by Django 5.0.6 on 2024-05-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("section", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("retrieval_value", models.CharField(max_length=255)),
                ("override_target", models.BooleanField(default=False, null=True)),
                ("new_target", models.TextField(max_length=255, null=True)),
                (
                    "retrieval_method",
                    models.CharField(
                        choices=[
                            ("FILE", "Read file"),
                            ("BASH", "Bash command"),
                            ("PW", "Powershell command"),
                            ("CMD", "Cmd command"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "retrieval_output",
                    models.CharField(
                        choices=[
                            ("PTXT", "Plain text"),
                            ("JSON", "JSON format"),
                            ("TBLE", "Table format"),
                            ("REGX", "Regex processing"),
                            ("GREP", "Grep command output"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("options", models.JSONField(null=True)),
                ("order", models.IntegerField(default=1)),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="section.section",
                    ),
                ),
            ],
        )
    ]
