# Generated by Django 3.2 on 2021-10-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_section_retrival_output'),
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='section.section'),
        ),
    ]
