# Generated by Django 3.2 on 2021-10-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0003_alter_section_template"),
        ("field", "0002_alter_field_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="section.section",
            ),
        ),
    ]
