# Generated by Django 3.2 on 2021-10-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_alter_section_template'),
        ('field', '0002_alter_field_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='section.section'),
        ),
    ]
