# Generated by Django 4.2.4 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_alter_field_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='new_target',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='options',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='override_target',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='retrival_method',
            field=models.CharField(choices=[('FILE', 'Read file'), ('BASH', 'Bash command'), ('PW', 'Powershell command'), ('CMD', 'Cmd command')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='retrival_output',
            field=models.CharField(choices=[('PTXT', 'Plain text'), ('JSON', 'JSON format'), ('TBLE', 'Table format'), ('REGX', 'Regex processing'), ('GREP', 'Grep command output')], max_length=4, null=True),
        ),
    ]
