# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_redhat_linux_fields(apps, schema_editor):
    fields = [
        {
            "name": "DESCRIPTION",
            "retrieval_value": "Description:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "TYPE",
            "retrieval_value": "Type:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "SPEED",
            "retrieval_value": "Speed:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "MTU",
            "retrieval_value": "MTU:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "MAC ADDRESS",
            "retrieval_value": "MACAddress:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "STATUS",
            "retrieval_value": "Status:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "IP ADDRESS",
            "retrieval_value": "IPAddress:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "NETMASK",
            "retrieval_value": "Netmask:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "GATEWAY",
            "retrieval_value": "Gateway:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "NETWORK NUMBER",
            "retrieval_value": "NetworkNumber:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "NAME",
            "retrieval_value": "name",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="REPOSITORY",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "BASE URL",
            "retrieval_value": "base_url",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="REPOSITORY",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "NAME",
            "retrieval_value": "Name:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "PUBLISHER",
            "retrieval_value": "Publisher:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "VERSION",
            "retrieval_value": "Version:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "COMMENTS",
            "retrieval_value": "Summary:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "FILE SIZE",
            "retrieval_value": "Size:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "INSTALLATION DATE",
            "retrieval_value": "InstallDate:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "FROM",
            "retrieval_value": "From:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "ARCHITECTURE",
            "retrieval_value": "Architecture:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "MAJOR",
            "retrieval_value": "Major:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "MINOR",
            "retrieval_value": "Minor:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
        {
            "name": "PATCH",
            "retrieval_value": "Patch:\\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="RHEL"),
            ),
        },
    ]

    Field = apps.get_model("field", "Field")

    current_section = None
    order = 1
    for field in fields:
        section_obj = field["section"]
        section_name = section_obj.name if hasattr(section_obj, "name") else section_obj
        if section_name != current_section:
            current_section = section_name
            order = 1
        field["order"] = order
        order += 1
        try:
            Field.objects.create(**field)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0007_redhat_linux"),
        ("field", "0006_snmp"),
    ]

    operations = [
        migrations.RunPython(create_redhat_linux_fields),
    ]
