# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_debian_linux_fields(apps, schema_editor):
    fields = [
        {
            "name": "DESCRIPTION",
            "retrieval_value": r"Description:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "TYPE",
            "retrieval_value": r"Type:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "SPEED",
            "retrieval_value": r"Speed:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "MTU",
            "retrieval_value": r"MTU:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "MAC ADDRESS",
            "retrieval_value": r"MACAddress:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "STATUS",
            "retrieval_value": r"Status:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "IP ADDRESS",
            "retrieval_value": r"IPAddress:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "NETMASK",
            "retrieval_value": r"Netmask:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "GATEWAY",
            "retrieval_value": r"Gateway:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "NETWORK NUMBER",
            "retrieval_value": r"NetworkNumber:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="NETWORKS",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "NAME",
            "retrieval_value": r"([^\/]+$)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="REPOSITORY",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "BASE URL",
            "retrieval_value": r"(http[^\s]+)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="REPOSITORY",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "NAME",
            "retrieval_value": r"Name:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "PUBLISHER",
            "retrieval_value": r"Publisher:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "VERSION",
            "retrieval_value": r"Version:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "COMMENTS",
            "retrieval_value": r"Comments:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "FILE SIZE",
            "retrieval_value": r"FileSize:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "INSTALLATION DATE",
            "retrieval_value": r"InstallDate:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "FROM",
            "retrieval_value": r"From:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "ARCHITECTURE",
            "retrieval_value": r"Architecture:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "MAJOR",
            "retrieval_value": r"Major:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "MINOR",
            "retrieval_value": r"Minor:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
        {
            "name": "PATCH",
            "retrieval_value": r"Patch:\r*(.*)",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": {},
            "section": apps.get_model("section", "Section").objects.get(
                name="SOFTWARES",
                template=apps.get_model("template", "Template").objects.get(os="DEB"),
            ),
        },
    ]

    Field = apps.get_model("field", "Field")

    current_section = None
    order = 1
    for field in fields:
        section_obj = field["section"]
        section_name = section_obj.name if hasattr(section_obj, "name") else section_obj
        if section_name != current_section:
            current_section = section_name
            order = 1
        field["order"] = order
        order += 1
        try:
            Field.objects.create(**field)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0008_debian_linux"),
        ("field", "0007_redhat_linux"),
    ]

    operations = [
        migrations.RunPython(create_debian_linux_fields),
    ]
