# Generated by Django 6.0.6 on 2026-06-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0008_debian_linux'),
        ('section', '0008_debian_linux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='field',
            name='retrieval_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='section.section'),
        ),
    ]
