from django.db import migrations


def create_linux_extended_rhel_fields(apps, schema_editor):
    Field = apps.get_model("field", "Field")
    Section = apps.get_model("section", "Section")
    Template = apps.get_model("template", "Template")

    template = Template.objects.get(name="Linux Extended (RHEL based)", os="RHEL")

    fields = [
        # VIRTUAL MACHINES section fields
        {
            "name": 'NAME',
            "order": 1,
            "retrieval_value": '"(.*)"',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='VIRTUAL MACHINES', template=template),
        },
        {
            "name": 'UUID',
            "order": 2,
            "retrieval_value": '\\{(.*)\\}',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='VIRTUAL MACHINES', template=template),
        },
        # REPOSITORY section fields
        {
            "name": 'NAME',
            "order": 1,
            "retrieval_value": 'name',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='REPOSITORY', template=template),
        },
        {
            "name": 'BASE URL',
            "order": 2,
            "retrieval_value": 'base_url',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='REPOSITORY', template=template),
        },
        # UPTIME section fields
        {
            "name": 'DURATION',
            "order": 1,
            "retrieval_value": 'DURATION=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='UPTIME', template=template),
        },
        {
            "name": 'LOG DATE',
            "order": 2,
            "retrieval_value": 'LOG_DATE=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='UPTIME', template=template),
        },
        # VIDEOS section fields
        {
            "name": 'NAME',
            "order": 1,
            "retrieval_value": 'Name\\s*:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='VIDEOS', template=template),
        },
        {
            "name": 'CHIPSET',
            "order": 2,
            "retrieval_value": 'Chipset\\s*:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='VIDEOS', template=template),
        },
        {
            "name": 'MEMORY',
            "order": 3,
            "retrieval_value": 'Memory\\s*:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='VIDEOS', template=template),
        },
        # BIOS section fields
        {
            "name": 'MANUFACTURER',
            "order": 1,
            "retrieval_value": 'DMI\\s+type\\s+1,.*?\\n(?:.*\\n)*?\\s*Manufacturer:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'MODEL',
            "order": 2,
            "retrieval_value": 'DMI\\s+type\\s+1,.*?\\n(?:.*\\n)*?\\s*Product Name:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'SERIAL NUMBER',
            "order": 3,
            "retrieval_value": 'DMI\\s+type\\s+1,.*?\\n(?:.*\\n)*?\\s*Serial Number:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'TYPE',
            "order": 4,
            "retrieval_value": 'DMI\\s+type\\s+3,.*?\\n(?:.*\\n)*?\\s*Type:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'BIOS MANUFACTURER',
            "order": 5,
            "retrieval_value": 'DMI\\s+type\\s+0,.*?\\n(?:.*\\n)*?\\s*Vendor:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'BIOS VERSION',
            "order": 6,
            "retrieval_value": 'DMI\\s+type\\s+0,.*?\\n(?:.*\\n)*?\\s*Version:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'BIOS DATE',
            "order": 7,
            "retrieval_value": 'DMI\\s+type\\s+0,.*?\\n(?:.*\\n)*?\\s*Release Date:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'ASSET TAG',
            "order": 8,
            "retrieval_value": 'DMI\\s+type\\s+(2|3),.*?\\n(?:.*\\n)*?\\s*Asset Tag:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'MOTHERBOARD MANUFACTURER',
            "order": 9,
            "retrieval_value": 'DMI\\s+type\\s+2,.*?\\n(?:.*\\n)*?\\s*Manufacturer:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'MOTHERBOARD MODEL',
            "order": 10,
            "retrieval_value": 'DMI\\s+type\\s+2,.*?\\n(?:.*\\n)*?\\s*Product Name:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        {
            "name": 'MOTHERBOARD SERIAL NUMBER',
            "order": 11,
            "retrieval_value": 'DMI\\s+type\\s+2,.*?\\n(?:.*\\n)*?\\s*Serial Number:\\s*(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BIOS', template=template),
        },
        # CONTROLLERS section fields
        {
            "name": 'MANUFACTURER',
            "order": 1,
            "retrieval_value": 'Vendor:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CONTROLLERS', template=template),
        },
        {
            "name": 'NAME',
            "order": 2,
            "retrieval_value": 'Device:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CONTROLLERS', template=template),
        },
        {
            "name": 'CAPTION',
            "order": 3,
            "retrieval_value": 'Slot:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CONTROLLERS', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 4,
            "retrieval_value": 'SDevice:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CONTROLLERS', template=template),
        },
        {
            "name": 'VERSION',
            "order": 5,
            "retrieval_value": 'Rev:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CONTROLLERS', template=template),
        },
        {
            "name": 'TYPE',
            "order": 6,
            "retrieval_value": 'Class:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CONTROLLERS', template=template),
        },
        # CPUS section fields
        {
            "name": 'MANUFACTURER',
            "order": 1,
            "retrieval_value": 'Vendor ID:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'TYPE',
            "order": 2,
            "retrieval_value": 'Model name:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'SERIAL NUMBER',
            "order": 3,
            "retrieval_value": 'Serial Number:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'FREQUENCY',
            "order": 4,
            "retrieval_value": 'Max Speed:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'CORES NUMBER',
            "order": 5,
            "retrieval_value": 'Core\\(s\\) per socket:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'L2 CACHE SIZE',
            "order": 6,
            "retrieval_value": 'L2 cache:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'ARCHITECTURE',
            "order": 7,
            "retrieval_value": 'Architecture:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'DATA WIDTH',
            "order": 8,
            "retrieval_value": 'CPU op-mode\\(s\\):\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'CURRENT ADDRESS WIDTH',
            "order": 9,
            "retrieval_value": 'Address sizes:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'LOGICAL CPUS',
            "order": 10,
            "retrieval_value": 'CPU\\(s\\):\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'VOLTAGE',
            "order": 11,
            "retrieval_value": 'Voltage:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'CURRENT SPEED',
            "order": 12,
            "retrieval_value": 'CPU max MHz:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        {
            "name": 'SOCKET TYPE',
            "order": 13,
            "retrieval_value": 'Socket Designation:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CPUS', template=template),
        },
        # DRIVES section fields
        {
            "name": 'DESIGNATION',
            "order": 1,
            "retrieval_value": 'Filesystem:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='DRIVES', template=template),
        },
        {
            "name": 'TYPE',
            "order": 2,
            "retrieval_value": 'Mounted:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='DRIVES', template=template),
        },
        {
            "name": 'FILE SYSTEM',
            "order": 3,
            "retrieval_value": 'Type:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='DRIVES', template=template),
        },
        {
            "name": 'TOTAL (MB)',
            "order": 4,
            "retrieval_value": 'Size_MB:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='DRIVES', template=template),
        },
        {
            "name": 'FREE (MB)',
            "order": 5,
            "retrieval_value": 'Avail_MB:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='DRIVES', template=template),
        },
        {
            "name": 'CAPACITY',
            "order": 6,
            "retrieval_value": 'Use%:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='DRIVES', template=template),
        },
        # INPUTS section fields
        {
            "name": 'TYPE',
            "order": 1,
            "retrieval_value": 'Type:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='INPUTS', template=template),
        },
        {
            "name": 'MANUFACTURER',
            "order": 2,
            "retrieval_value": 'Manufacturer:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='INPUTS', template=template),
        },
        {
            "name": 'CAPTION',
            "order": 3,
            "retrieval_value": 'Caption:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='INPUTS', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 4,
            "retrieval_value": 'Description:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='INPUTS', template=template),
        },
        {
            "name": 'INTERFACE',
            "order": 5,
            "retrieval_value": 'Interface:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='INPUTS', template=template),
        },
        # LOCAL GROUPS section fields
        {
            "name": 'GROUP ID',
            "order": 1,
            "retrieval_value": '^[^:]+:[^:]*:([0-9]+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL GROUPS', template=template),
        },
        {
            "name": 'MEMBER',
            "order": 2,
            "retrieval_value": '^[^:]+:[^:]*:[0-9]+:([^\\n]*)$',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL GROUPS', template=template),
        },
        {
            "name": 'NAME',
            "order": 3,
            "retrieval_value": '^([^:]+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL GROUPS', template=template),
        },
        # LOCAL USERS section fields
        {
            "name": 'USER ID',
            "order": 1,
            "retrieval_value": '^[^:]+:[^:]*:([0-9]+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL USERS', template=template),
        },
        {
            "name": 'GROUP ID',
            "order": 2,
            "retrieval_value": '^[^:]+:[^:]*:[0-9]+:([0-9]+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL USERS', template=template),
        },
        {
            "name": 'NAME',
            "order": 3,
            "retrieval_value": '^([^:]+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL USERS', template=template),
        },
        {
            "name": 'HOME',
            "order": 4,
            "retrieval_value": '^(?:[^:]*:){5}([^:]*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL USERS', template=template),
        },
        {
            "name": 'SHELL',
            "order": 5,
            "retrieval_value": '^(?:[^:]*:){6}([^:\\n]*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL USERS', template=template),
        },
        {
            "name": 'LOGIN',
            "order": 6,
            "retrieval_value": '^([^:]+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='LOCAL USERS', template=template),
        },
        # MEMORIES section fields
        {
            "name": 'CAPTION',
            "order": 1,
            "retrieval_value": 'Bank Locator:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MEMORIES', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 2,
            "retrieval_value": 'Type Detail:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MEMORIES', template=template),
        },
        {
            "name": 'CAPACITY',
            "order": 3,
            "retrieval_value": 'Size:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MEMORIES', template=template),
        },
        {
            "name": 'PURPOSE',
            "order": 4,
            "retrieval_value": 'Set:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MEMORIES', template=template),
        },
        {
            "name": 'TYPE',
            "order": 5,
            "retrieval_value": 'Type:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MEMORIES', template=template),
        },
        {
            "name": 'SPEED',
            "order": 6,
            "retrieval_value": 'Speed:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MEMORIES', template=template),
        },
        {
            "name": 'SLOT NUMBER',
            "order": 7,
            "retrieval_value": 'Locator:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MEMORIES', template=template),
        },
        {
            "name": 'SERIAL NUMBER',
            "order": 8,
            "retrieval_value": 'Serial Number:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MEMORIES', template=template),
        },
        # MONITORS section fields
        {
            "name": 'MANUFACTURER',
            "order": 1,
            "retrieval_value": 'Vendor:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MONITORS', template=template),
        },
        {
            "name": 'CAPTION',
            "order": 2,
            "retrieval_value": "(?:Display Product Name|Alphanumeric Data String):\\s*'?([^']*)'?",
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MONITORS', template=template),
        },
        {
            "name": 'MANUFACTURED ON (WEEK/YEAR)',
            "order": 3,
            "retrieval_value": 'Made in:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MONITORS', template=template),
        },
        {
            "name": 'TYPE',
            "order": 4,
            "retrieval_value": '(Digital display|Analog display)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MONITORS', template=template),
        },
        {
            "name": 'SERIAL NUMBER',
            "order": 5,
            "retrieval_value": 'Serial Number:\\s*([0-9]+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='MONITORS', template=template),
        },
        # NETWORKS section fields
        {
            "name": 'DESCRIPTION',
            "order": 1,
            "retrieval_value": 'Description:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'TYPE',
            "order": 2,
            "retrieval_value": 'Type:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'SPEED',
            "order": 3,
            "retrieval_value": 'Speed:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'MTU',
            "order": 4,
            "retrieval_value": 'MTU:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'MAC ADDRESS',
            "order": 5,
            "retrieval_value": 'MACAddress:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'STATUS',
            "order": 6,
            "retrieval_value": 'Status:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'IP ADDRESS',
            "order": 7,
            "retrieval_value": 'IPAddress:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'NETMASK',
            "order": 8,
            "retrieval_value": 'Netmask:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'GATEWAY',
            "order": 9,
            "retrieval_value": 'Gateway:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        {
            "name": 'NETWORK NUMBER',
            "order": 10,
            "retrieval_value": 'NetworkNumber:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='NETWORKS', template=template),
        },
        # PORTS section fields
        {
            "name": 'TYPE',
            "order": 1,
            "retrieval_value": 'Port Type\\s*:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='PORTS', template=template),
        },
        {
            "name": 'NAME',
            "order": 2,
            "retrieval_value": 'Internal Reference Designator\\s*:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='PORTS', template=template),
        },
        {
            "name": 'CAPTION',
            "order": 3,
            "retrieval_value": 'External Connector Type\\s*:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='PORTS', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 4,
            "retrieval_value": 'Internal Connector Type\\s*:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='PORTS', template=template),
        },
        # PRINTERS section fields
        {
            "name": 'NAME',
            "order": 1,
            "retrieval_value": 'Name:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='PRINTERS', template=template),
        },
        {
            "name": 'DRIVER',
            "order": 2,
            "retrieval_value": 'DRIVER:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='PRINTERS', template=template),
        },
        {
            "name": 'PORT',
            "order": 3,
            "retrieval_value": 'Port:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='PRINTERS', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 4,
            "retrieval_value": 'Description:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='PRINTERS', template=template),
        },
        # SLOTS section fields
        {
            "name": 'NAME',
            "order": 1,
            "retrieval_value": 'Designation\\s*:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SLOTS', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 2,
            "retrieval_value": 'Type\\s*:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SLOTS', template=template),
        },
        {
            "name": 'DESIGNATION',
            "order": 3,
            "retrieval_value": 'ID\\s*:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SLOTS', template=template),
        },
        {
            "name": 'STATUS',
            "order": 4,
            "retrieval_value": 'Current Usage\\s*:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SLOTS', template=template),
        },
        # SOUNDS section fields
        {
            "name": 'MANUFACTURER',
            "order": 1,
            "retrieval_value": 'Vendor:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOUNDS', template=template),
        },
        {
            "name": 'NAME',
            "order": 2,
            "retrieval_value": 'Device:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOUNDS', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 3,
            "retrieval_value": 'Class:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOUNDS', template=template),
        },
        # STORAGES section fields
        {
            "name": 'MANUFACTURER',
            "order": 1,
            "retrieval_value": 'Manufacturer:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='STORAGES', template=template),
        },
        {
            "name": 'NAME',
            "order": 2,
            "retrieval_value": 'Name:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='STORAGES', template=template),
        },
        {
            "name": 'MODEL',
            "order": 3,
            "retrieval_value": 'Model:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='STORAGES', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 4,
            "retrieval_value": 'Description:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='STORAGES', template=template),
        },
        {
            "name": 'TYPE',
            "order": 5,
            "retrieval_value": 'Type:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='STORAGES', template=template),
        },
        {
            "name": 'DISK SIZE',
            "order": 6,
            "retrieval_value": 'DiskSize:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='STORAGES', template=template),
        },
        {
            "name": 'SERIAL NUMBER',
            "order": 7,
            "retrieval_value": 'SerialNumber:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='STORAGES', template=template),
        },
        {
            "name": 'FIRMWARE',
            "order": 8,
            "retrieval_value": 'Firmware:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='STORAGES', template=template),
        },
        # USB DEVICES section fields
        {
            "name": 'DESCRIPTION',
            "order": 1,
            "retrieval_value": 'iProduct\\s*\\d+\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='USB DEVICES', template=template),
        },
        {
            "name": 'INTERFACE',
            "order": 2,
            "retrieval_value": 'bInterfaceSubClass\\s*\\d+\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='USB DEVICES', template=template),
        },
        {
            "name": 'MANUFACTURER',
            "order": 3,
            "retrieval_value": 'iManufacturer\\s*\\d+\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='USB DEVICES', template=template),
        },
        {
            "name": 'SERIAL NUMBER',
            "order": 4,
            "retrieval_value": 'iSerial\\s*\\d+\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='USB DEVICES', template=template),
        },
        {
            "name": 'TYPE',
            "order": 5,
            "retrieval_value": 'bInterfaceClass\\s*\\d+\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='USB DEVICES', template=template),
        },
        # BATTERIES section fields
        {
            "name": 'CHEMISTRY',
            "order": 1,
            "retrieval_value": 'technology:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'CYCLES',
            "order": 2,
            "retrieval_value": 'charge-cycles:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'DESCRIPTION',
            "order": 3,
            "retrieval_value": 'model:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'DESIGN CAPACITY',
            "order": 4,
            "retrieval_value": 'energy-full-design:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'DESIGN VOLTAGE',
            "order": 5,
            "retrieval_value": 'voltage:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'ESTIMATED CHARGE REMAINING',
            "order": 6,
            "retrieval_value": 'percentage:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'MANUFACTURER',
            "order": 7,
            "retrieval_value": 'vendor:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'NAME',
            "order": 8,
            "retrieval_value": 'native-path:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'SERIAL NUMBER',
            "order": 9,
            "retrieval_value": 'serial:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        {
            "name": 'STATUS',
            "order": 10,
            "retrieval_value": 'state:\\s*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='BATTERIES', template=template),
        },
        # SOFTWARES section fields
        {
            "name": 'NAME',
            "order": 1,
            "retrieval_value": 'Name:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'PUBLISHER',
            "order": 2,
            "retrieval_value": 'Publisher:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'VERSION',
            "order": 3,
            "retrieval_value": 'Version:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'COMMENTS',
            "order": 4,
            "retrieval_value": 'Summary:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'FILE SIZE',
            "order": 5,
            "retrieval_value": 'Size:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'INSTALLATION DATE',
            "order": 6,
            "retrieval_value": 'InstallDate:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'FROM',
            "order": 7,
            "retrieval_value": 'From:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'ARCHITECTURE',
            "order": 8,
            "retrieval_value": 'Architecture:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'MAJOR',
            "order": 9,
            "retrieval_value": 'Major:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'MINOR',
            "order": 10,
            "retrieval_value": 'Minor:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        {
            "name": 'PATCH',
            "order": 11,
            "retrieval_value": 'Patch:\\r*(.*)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SOFTWARES', template=template),
        },
        # SECURITY CERTIFICATE section fields
        {
            "name": 'NAME',
            "order": 1,
            "retrieval_value": 'NAME=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SECURITY CERTIFICATE', template=template),
        },
        {
            "name": 'AUTORITY',
            "order": 2,
            "retrieval_value": 'AUTHORITY=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SECURITY CERTIFICATE', template=template),
        },
        {
            "name": 'DATE START',
            "order": 3,
            "retrieval_value": 'DATESTART=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SECURITY CERTIFICATE', template=template),
        },
        {
            "name": 'EXPIRATION',
            "order": 4,
            "retrieval_value": 'EXPIRATION=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='SECURITY CERTIFICATE', template=template),
        },
        # TEAM VIEWER section fields
        {
            "name": 'ID',
            "order": 1,
            "retrieval_value": 'TWID=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='TEAM VIEWER', template=template),
        },
        {
            "name": 'VERSION',
            "order": 2,
            "retrieval_value": 'VERSION=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='TEAM VIEWER', template=template),
        },
        # FIREWALL RULES section fields
        {
            "name": 'DIRECTION',
            "order": 1,
            "retrieval_value": 'DIRECTION=(\\S+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='FIREWALL RULES', template=template),
        },
        {
            "name": 'SOURCE',
            "order": 2,
            "retrieval_value": 'SOURCE=(\\S+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='FIREWALL RULES', template=template),
        },
        {
            "name": 'SOURCE PORT',
            "order": 3,
            "retrieval_value": 'SRC_PORT=(\\S+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='FIREWALL RULES', template=template),
        },
        {
            "name": 'DESTINATION',
            "order": 4,
            "retrieval_value": 'DESTINATION=(\\S+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='FIREWALL RULES', template=template),
        },
        {
            "name": 'DESTINATION PORT',
            "order": 5,
            "retrieval_value": 'DST_PORT=(\\S+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='FIREWALL RULES', template=template),
        },
        {
            "name": 'ACTION',
            "order": 6,
            "retrieval_value": 'ACTION=(\\S+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='FIREWALL RULES', template=template),
        },
        {
            "name": 'PROTOCOL',
            "order": 7,
            "retrieval_value": 'PROTOCOL=(\\S+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='FIREWALL RULES', template=template),
        },
        # REDHAT ERRATA section fields
        {
            "name": 'ERRATA',
            "order": 1,
            "retrieval_value": 'ERRATA=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='REDHAT ERRATA', template=template),
        },
        {
            "name": 'PACKAGE',
            "order": 2,
            "retrieval_value": 'PACKAGE=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='REDHAT ERRATA', template=template),
        },
        {
            "name": 'SEVERITY',
            "order": 3,
            "retrieval_value": 'SEVERITY=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='REDHAT ERRATA', template=template),
        },
        {
            "name": 'TYPE',
            "order": 4,
            "retrieval_value": 'TYPE=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='REDHAT ERRATA', template=template),
        },
        {
            "name": 'UPDATED',
            "order": 5,
            "retrieval_value": 'UPDATED=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='REDHAT ERRATA', template=template),
        },
        # CRON TAB TASKS section fields
        {
            "name": 'MINUTE',
            "order": 1,
            "retrieval_value": 'MINUTE=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CRON TAB TASKS', template=template),
        },
        {
            "name": 'HOUR',
            "order": 2,
            "retrieval_value": 'HOUR=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CRON TAB TASKS', template=template),
        },
        {
            "name": 'DOM',
            "order": 3,
            "retrieval_value": 'DOM=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CRON TAB TASKS', template=template),
        },
        {
            "name": 'MONTH',
            "order": 4,
            "retrieval_value": 'MONTH=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CRON TAB TASKS', template=template),
        },
        {
            "name": 'DOW',
            "order": 5,
            "retrieval_value": 'DOW=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CRON TAB TASKS', template=template),
        },
        {
            "name": 'USER',
            "order": 6,
            "retrieval_value": 'USER=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CRON TAB TASKS', template=template),
        },
        {
            "name": 'CRON',
            "order": 7,
            "retrieval_value": 'CRON=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='CRON TAB TASKS', template=template),
        },
        # RUNNING PROCESS section fields
        {
            "name": 'USERNAME',
            "order": 1,
            "retrieval_value": 'USERNAME=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='RUNNING PROCESS', template=template),
        },
        {
            "name": 'PROCESS ID',
            "order": 2,
            "retrieval_value": 'PROCESSID=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='RUNNING PROCESS', template=template),
        },
        {
            "name": 'CPU USAGE',
            "order": 3,
            "retrieval_value": 'CPUUSAGE=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='RUNNING PROCESS', template=template),
        },
        {
            "name": 'PROCESS MEMORY',
            "order": 4,
            "retrieval_value": 'PROCESSMEMORY=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='RUNNING PROCESS', template=template),
        },
        {
            "name": 'VIRTUAL MEMORY',
            "order": 5,
            "retrieval_value": 'VIRTUALMEMORY=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='RUNNING PROCESS', template=template),
        },
        {
            "name": 'TTY',
            "order": 6,
            "retrieval_value": 'TTY=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='RUNNING PROCESS', template=template),
        },
        {
            "name": 'STARTED',
            "order": 7,
            "retrieval_value": 'STARTED=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='RUNNING PROCESS', template=template),
        },
        {
            "name": 'COMMANDLINE',
            "order": 8,
            "retrieval_value": 'COMMANDLINE=(.+)',
            "override_target": False,
            "new_target": None,
            "retrieval_method": None,
            "retrieval_output": None,
            "options": None,
            "section": Section.objects.get(name='RUNNING PROCESS', template=template),
        },
    ]

    for field in fields:
        try:
            Field.objects.create(**field)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0013_linux_extended_rhel"),
        ("field", "0012_linux_extended_debian"),
    ]

    operations = [
        migrations.RunPython(create_linux_extended_rhel_fields),
    ]
