# Generated by Django 5.0.6 on 2024-12-19 10:57

from django.db import migrations
from django.contrib.auth.management import create_permissions


def create_default_permissions(apps, schema_editor):
    """
    Create default permissions
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


class Migration(migrations.Migration):

    dependencies = [
        ("auth_config", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_permissions)]
