# Generated by Django 4.2.3 on 2024-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("SSO", "SSO"), ("OTHER", "OTHER")], max_length=255
                    ),
                ),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
