# Generated by Django 4.2.3 on 2024-01-15 09:39

from django.db import migrations


def create_default_groups(apps, schema_editor):
    """
    Create default groups : super-admin / admin / user
    """
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="super-admin")
    Group.objects.get_or_create(name="admin")
    Group.objects.get_or_create(name="user")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_groups)]
