# Generated by Django 5.2.11 on 2026-02-16 00:00

import django.db.models.deletion
from django.db import migrations, models


def create_group_protection_entries(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    GroupProtection = apps.get_model("group", "GroupProtection")
    default_protected_groups = {"super-admin", "admin", "user"}

    for group in Group.objects.all():
        is_protected = group.name in default_protected_groups
        GroupProtection.objects.update_or_create(
            group_id=group.id,
            defaults={"is_protected": is_protected},
        )


def remove_group_protection_entries(apps, schema_editor):
    GroupProtection = apps.get_model("group", "GroupProtection")
    GroupProtection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProtection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_protected", models.BooleanField(default=False)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protection",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_group_protection_entries,
            remove_group_protection_entries,
        ),
    ]
