# Generated by Django 4.2.7 on 2025-04-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snmp_config', '0001_initial'),
        ('inventory_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnmpScanner',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('subnets', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_scanned', models.IntegerField(default=0, null=True)),
                ('total_found', models.IntegerField(default=0, null=True)),
                ('last_scan_date', models.DateTimeField(null=True)),
                ('assets', models.ManyToManyField(blank=True, to='inventory_base.inventorybase')),
                ('configs', models.ManyToManyField(blank=True, to='snmp_config.snmpconfig')),
            ],
        ),
    ]
