# Generated by Django 6.0.6 on 2026-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory_base", "0001_initial"),
        ("snmp_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnmpScanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("ip", models.GenericIPAddressField()),
                ("subnets", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("total_scanned", models.IntegerField(default=0, null=True)),
                ("total_found", models.IntegerField(default=0, null=True)),
                ("last_scan_date", models.DateTimeField(null=True)),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True, to="inventory_base.inventorybase"
                    ),
                ),
                (
                    "configs",
                    models.ManyToManyField(blank=True, to="snmp_config.snmpconfig"),
                ),
            ],
        ),
    ]
