# Generated by Django 6.0.6 on 2026-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SnmpConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "version",
                    models.CharField(
                        choices=[("1", "SNMPv1"), ("2c", "SNMPv2c"), ("3", "SNMPv3")],
                        max_length=3,
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "auth_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("noAuthNoPriv", "noAuthNoPriv"),
                            ("authNoPriv", "authNoPriv"),
                            ("authPriv", "authPriv"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "auth_protocol",
                    models.CharField(
                        blank=True,
                        choices=[("MD5", "MD5"), ("SHA", "SHA"), ("None", "None")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "priv_protocol",
                    models.CharField(
                        blank=True,
                        choices=[("DES", "DES"), ("AES", "AES"), ("None", "None")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "priv_password",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("retries", models.IntegerField(default=3)),
                ("timeout", models.IntegerField(default=3)),
                ("subnets", models.JSONField()),
            ],
        ),
    ]
