# Generated by Django 3.2 on 2021-12-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountinfoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('datatype', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('SELECT', 'Select'), ('CHECKBOX', 'Checkbox')], default='TEXT', max_length=10)),
                ('datatarget', models.CharField(choices=[('ASSET', 'Assets'), ('SNMP', 'SNMP'), ('IPDISCOVER', 'IPDiscover')], default='ASSET', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AccountinfoValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('accountinfo_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountinfo_config', to='accountinfo.accountinfoconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AccountinfoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountdata', models.JSONField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
