# Generated by Django 3.2 on 2021-12-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("accountinfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountinfodata",
            name="object_slug",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="accountinfodata",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="accountinfovalue",
            name="accountinfo_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accountinfo_values",
                to="accountinfo.accountinfoconfig",
            ),
        ),
    ]
