# Generated by Django 3.2 on 2021-12-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfodata',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='accountinfodata',
            name='object_id',
        ),
    ]
