# Generated by Django 6.0.6 on 2026-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('target_os', models.CharField(choices=[('WIN', 'Windows'), ('LIN', 'Linux'), ('MAC', 'Mac')], default='WIN', max_length=3)),
            ],
        ),
    ]
