# Generated by Django 4.2.4 on 2023-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='target_os',
            field=models.CharField(choices=[('WIN', 'Windows'), ('LIN', 'Linux'), ('MAC', 'Mac')], default='WIN', max_length=3),
        ),
    ]
