# Generated by Django 3.2 on 2022-11-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_alter_base_id'),
        ('package', '0002_alter_package_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=128)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_history', to='base.base')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_history', to='package.package')),
            ],
        ),
    ]
