# Generated by Django 3.2 on 2022-11-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='package_id',
            new_name='package',
        ),
    ]
