# Generated by Django 3.2 on 2022-11-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_rename_package_id_history_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='asset_id',
            new_name='asset',
        ),
    ]
