# Generated by Django 4.2.3 on 2024-07-03 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_layout(apps, schema_editor):
    DashboardLayout = apps.get_model("layout", "DashboardLayout")
    default_layout = DashboardLayout(
        visibility="public",
        allow_group_modification=False,
        name="Default Layout",
        user_id=1,
        layout=[
            {
                "x": 0,
                "y": 0,
                "w": 2,
                "h": 4,
                "i": 0,
                "minw": 2,
                "minh": 4,
                "name": "total_ALL",
                "type": "Counter",
                "resizable": True,
            },
            {
                "x": 2,
                "y": 0,
                "w": 2,
                "h": 4,
                "i": 1,
                "minw": 2,
                "minh": 4,
                "name": "total_WIN",
                "type": "Counter",
                "resizable": True,
            },
            {
                "x": 4,
                "y": 0,
                "w": 2,
                "h": 4,
                "i": 2,
                "minw": 2,
                "minh": 4,
                "name": "total_LIN",
                "type": "Counter",
                "resizable": True,
            },
            {
                "x": 6,
                "y": 0,
                "w": 2,
                "h": 4,
                "i": 3,
                "minw": 2,
                "minh": 4,
                "name": "total_MAC",
                "type": "Counter",
                "resizable": True,
            },
            {
                "x": 8,
                "y": 0,
                "w": 2,
                "h": 4,
                "i": 4,
                "minw": 2,
                "minh": 4,
                "name": "total_LEG",
                "type": "Counter",
                "resizable": True,
            },
            {
                "x": 10,
                "y": 0,
                "w": 2,
                "h": 4,
                "i": 5,
                "minw": 2,
                "minh": 4,
                "name": "total_SNMP",
                "type": "Counter",
                "resizable": True,
            },
            {
                "x": 0,
                "y": 4,
                "w": 6,
                "h": 9,
                "i": 6,
                "minw": 6,
                "minh": 10,
                "name": "oscount",
                "type": "DonutChart",
                "resizable": False,
            },
            {
                "x": 6,
                "y": 4,
                "w": 6,
                "h": 9,
                "i": 7,
                "minw": 6,
                "minh": 10,
                "name": "lastcontacted",
                "type": "LineChart",
                "resizable": False,
            },
            {
                "x": 0,
                "y": 14,
                "w": 6,
                "h": 3,
                "i": 8,
                "minw": 2,
                "minh": 3,
                "name": "nb_networks",
                "type": "Counter",
                "resizable": True,
            },
            {
                "x": 6,
                "y": 14,
                "w": 6,
                "h": 3,
                "i": 9,
                "minw": 2,
                "minh": 3,
                "name": "nb_netdevices",
                "type": "Counter",
                "resizable": True,
            },
            {
                "x": 3,
                "y": 17,
                "w": 6,
                "h": 9,
                "i": 10,
                "minw": 6,
                "minh": 9,
                "name": "networks",
                "type": "BarChart",
                "resizable": False,
            },
        ],
    )
    default_layout.save()


class Migration(migrations.Migration):

    initial = True

    # this migration will fail if the default user is not created yet
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private_personal", "Private (Personal)"),
                            ("private_group", "Private (Group)"),
                        ],
                        default="private_personal",
                        max_length=20,
                    ),
                ),
                ("allow_group_modification", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("layout", models.JSONField()),
                ("groups", models.ManyToManyField(blank=True, to="auth.group")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_default_layout),
    ]
