# Generated by Django 4.2.3 on 2024-07-03 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_layout(apps, schema_editor):
    DashboardLayout = apps.get_model('dashboard.layout', 'DashboardLayout')
    default_layout = DashboardLayout(
        visibility='public',
        allow_group_modification=False,
        name='Default Layout',
        layout=[
            {
                "x": 0,
                "y": 0,
                "w": 3,
                "h": 4,
                "i": "total",
                "static": False
            },
            {
                "x": 3,
                "y": 0,
                "w": 3,
                "h": 4,
                "i": "contacted",
                "static": False
            },
            {
                "x": 6,
                "y": 0,
                "w": 3,
                "h": 4,
                "i": "lastcontacted",
                "static": False
            },
            {
                "x": 9,
                "y": 0,
                "w": 3,
                "h": 4,
                "i": "oscount",
                "static": False
            },
            {
                "x": 0,
                "y": 4,
                "w": 6,
                "h": 8,
                "i": "networks",
                "static": False
            },
            {
                "x": 6,
                "y": 4,
                "w": 6,
                "h": 8,
                "i": "netdevices",
                "static": False
            }
        ],
    )
    default_layout.save()


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private_personal', 'Private (Personal)'), ('private_group', 'Private (Group)')], default='private_personal', max_length=20)),
                ('allow_group_modification', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('layout', models.JSONField()),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_default_layout),
    ]
