"""
Django settings for ocsinventory_backend project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "django_extensions",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "user.apps.UserConfig",
    "group.apps.GroupConfig",
    "permission.apps.PermissionConfig",
    "config.apps.ConfigConfig",
    "mgmt.apps.MgmtConfig",
    "inventory.template.apps.TemplateConfig",
    "inventory.section.apps.SectionConfig",
    "inventory.field.apps.FieldConfig",
    "inventory.category.apps.CategoryConfig",
    "ipdiscover.netdevice.apps.NetdeviceConfig",
    "ipdiscover.network.apps.NetworkConfig",
    "ipdiscover.netgroup.apps.NetgroupConfig",
    "snmp.scanner.apps.SnmpScannerConfig",
    "snmp.snmp_config.apps.SnmpConfigConfig",
    "accountinfo.apps.AccountinfoConfig",
    "asset.log.apps.LogConfig",
    "automation.scheduler.apps.SchedulerConfig",
    "automation.history.apps.HistoryConfig",
    "automation.rule.apps.RuleConfig",
    "asset.inventory_base.apps.InventoryBaseConfig",
    "asset.inventory_section.apps.InventorySectionConfig",
    "asset.inventory_field.apps.InventoryFieldConfig",
    "asset.asset_group.apps.AssetGroupConfig",
    "deployment.package.apps.PackageConfig",
    "deployment.action.apps.ActionConfig",
    "deployment.result.apps.ResultConfig",
    "auth.auth_method.apps.AuthMethodConfig",
    "auth.auth_config.apps.AuthConfigConfig",
    "auth.auth_mapping.apps.AuthMappingConfig",
    "dashboard.layout.apps.DashboardLayoutConfig",
    "dashboard.chart.apps.DashboardChartConfig",
    "search.apps.SearchConfig",
    "django_cas_ng",
    "filemanager.apps.FileManagerConfig",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_cas_ng.middleware.CASMiddleware",
]

ROOT_URLCONF = "ocsinventory_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# App logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}][{asctime}][{name}:{funcName}:{lineno}]: {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}][{asctime}][{name}]: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "django": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/ocs_django.log",
            "when": "W6",
            "backupCount": 2,
            "formatter": "simple",
        },
        "ocs_backend": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/ocs_backend.log",
            "when": "W6",
            "backupCount": 2,
            "formatter": "verbose",
        },
        "ocs_collection": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/ocs_collection.log",
            "when": "W6",
            "backupCount": 2,
            "formatter": "verbose",
        },
        "ocs_management": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": f"{BASE_DIR}/logs/ocs_management.log",
            "when": "W6",
            "backupCount": 2,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["django"],
            "level": "INFO",
            "propagate": False,
        },
        # inventory collection  only
        "asset.collection.views": {
            "handlers": ["ocs_collection"],
            "level": "INFO",
            "propagate": False,
        },
        # root
        "": {
            "handlers": ["ocs_backend"],
            "level": "INFO",
        },
        # ipdiscover command logger
        "mgmt.management.commands": {
            "handlers": ["ocs_management"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


WSGI_APPLICATION = "ocsinventory_backend.wsgi.application"

# Rest Framework
REST_FRAMEWORK = {
    # Add default auth using Token Auth
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    # Use to permit the server to retreive data in JSON or XML.
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.JSONParser",
        "rest_framework_xml.parsers.XMLParser",
    ],
    # Use to permit the server to give a response in JSON or XML.
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework_xml.renderers.XMLRenderer",
    ],
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.DjangoModelPermissions",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%S%z",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# CORS Allow all during dev
CORS_ALLOW_ALL_ORIGINS = True

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# HSTS settings
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# SSL settings
SECURE_SSL_REDIRECT = False

# Session settings
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Media files

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Authentication
# Custom auth backend (specifies the backend class to use for authentication)
AUTHENTICATION_BACKENDS = ["auth.backends.AuthBackend"]

# List of customised auth backends (used to dynamically import
# backend classes in authentication process)
OCS_CUSTOM_AUTH_BACKENDS = {
    "CAS": "auth.auth_backend.cas_backend.CustomCASBackend",
    "LDAP": "auth.auth_backend.ldap_backend.CustomLDAPBackend",
    "OIDC": "auth.auth_backend.oidc_backend.CustomOIDCBackend",
}

# Schema settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'OCS Inventory API',
    'DESCRIPTION': 'Description détaillée',
    'VERSION': '1.0.0',
    'COMPONENT_SPLIT_REQUEST': True,

    'SERVERS': [
        {
            'url': '{protocol}://{host}:{port}',
            'variables': {
                'protocol': {
                    'default': 'http',
                    'enum': ['http', 'https'],
                    'description': 'Protocole'
                },
                'host': {
                    'default': 'localhost',
                    'description': 'Adresse IP ou Nom de domaine'
                },
                'port': {
                    'default': '8000',
                    'description': 'Port du serveur'
                },
            }
        }
    ],
}