# Generated by Django 3.2 on 2021-10-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('netid', models.GenericIPAddressField()),
                ('mask', models.GenericIPAddressField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netgroups', to='netgroup.netgroup')),
            ],
        ),
    ]
