# Generated by Django 6.0.6 on 2026-06-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nettag', models.CharField(default='DefaultNettag', max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('location', models.CharField(max_length=128, null=True)),
                ('netid', models.GenericIPAddressField()),
                ('mask', models.GenericIPAddressField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='netgroup.netgroup')),
            ],
        ),
    ]
