# Generated by Django 3.2 on 2021-10-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netgroup', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netgroups', to='netgroup.netgroup'),
        ),
    ]
