# Generated by Django 3.2 on 2021-10-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_network_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='location',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
