# Generated by Django 3.2 on 2021-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_network_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="nettag",
            field=models.CharField(
                default="DefaultNettag", max_length=128, unique=True
            ),
        ),
    ]
