# Generated by Django 4.2.4 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_network_nettag'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
