# Generated by Django 3.2 on 2021-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "os",
                    models.CharField(
                        choices=[("WIN", "Windows"), ("LIN", "Linux"), ("MAC", "Mac")],
                        default="WIN",
                        max_length=3,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
