# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations, models


def create_default_templates(apps, schema_editor):
    templates = [
        {
            "name": "Legacy",
            "os": "LEG",
            "is_protected": True,
        },
        {
            "name": "Linux",
            "os": "LIN",
            "is_protected": True,
        },
        {
            "name": "MacOS",
            "os": "MAC",
            "is_protected": True,
        },
        {
            "name": "Windows",
            "os": "WIN",
            "is_protected": True,
        },
        {
            "name": "SNMP Generic",
            "os": "SNMP",
            "is_protected": True,
        },
    ]

    Template = apps.get_model("template", "Template")

    for template in templates:
        try:
            Template.objects.create(**template)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("LEG", "Legacy"),
                            ("LIN", "Linux"),
                            ("MAC", "Mac"),
                            ("WIN", "Windows"),
                            ("SNMP", "SNMP"),
                        ],
                        default="WIN",
                        max_length=4,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("is_protected", models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_default_templates),
    ]
