# Generated by Django 4.2.7 on 2025-04-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='os',
            field=models.CharField(choices=[('LEG', 'Legacy'), ('LIN', 'Linux'), ('MAC', 'Mac'), ('WIN', 'Windows'), ('SNMP', 'Snmp')], default='WIN', max_length=4),
        ),
    ]
