# Generated by Django 4.2.3 on 2024-01-15 09:39

import django.db.models.deletion
from django.db import migrations, models


def add_auth_methods(apps, schema_editor):
    """
    This function is used to create AuthMethod, AuthConfig and
     AuthMapping initial data.
    """
    AuthMethod = apps.get_model("auth_method", "AuthMethod")
    AuthConfig = apps.get_model("auth_config", "AuthConfig")
    AuthMapping = apps.get_model("auth_mapping", "AuthMapping")

    auth_methods = [
        {"name": "LOCAL", "auth_type": "OTHER", "priority": 1, "enabled": True},
        {
            "name": "LDAP",
            "auth_type": "OTHER",
            "enabled": False,
            "priority": 2,
            "configs": [
                {
                    "enabled": True,
                    "priority": 1,
                    "config": {
                        "SERVER_URI": "ldap://127.0.0.1:3268",
                        "BIND_DN": "CN=Admin,CN=Users,DC=domain,DC=dc",
                        "BIND_PASSWORD": "password",
                        "BASE_DN": "CN=Users,DC=domain,DC=dc",
                        "USER_LOGIN_FIELD": "sAMAccountName",
                        "MIRROR_GROUPS": False,
                        "PROTOCOL_VERSION": 3,
                    },
                }
            ],
        },
        {
            "name": "OIDC",
            "auth_type": "SSO",
            "enabled": False,
            "priority": None,
            "configs": [
                {
                    "enabled": True,
                    "priority": None,
                    "config": {
                        "AUTHORIZATION_ENDPOINT": "https://auth.provider.org/protocol/openid-connect/auth",
                        "TOKEN_ENDPOINT": "https://auth.provider.org/protocol/openid-connect/token",
                        "USERINFO_ENDPOINT": "https://auth.provider.org/protocol/openid-connect/userinfo",
                        "CLIENT_ID": "test-openid",
                        "CLIENT_SECRET": "",
                        "SCOPES": "profile openid",
                        "PROXY": "",
                        "SIGN_ALGO": "RS256",
                        "JWKS_ENDPOINT": "https://auth.provider.org/protocol/openid-connect/certs",
                        "AUTO_REDIRECT": True,
                    },
                    "mappings": [
                        {"internal_field": "email", "external_field": "email"},
                        {
                            "internal_field": "username",
                            "external_field": "preferred_username",
                        },
                        {
                            "internal_field": "first_name",
                            "external_field": "given_name",
                        },
                        {
                            "internal_field": "last_name",
                            "external_field": "family_name",
                        },
                    ],
                }
            ],
        },
        {
            "name": "CAS",
            "auth_type": "SSO",
            "enabled": False,
            "priority": None,
            "configs": [
                {
                    "enabled": True,
                    "priority": None,
                    "config": {
                        "SERVER_URL": "http://auth.provider.org/protocol/cas/",
                        "LOGIN_ROUTE": "login",
                        "LOGOUT_ROUTE": "logout",
                        "VERSION": 2,
                        "AUTO_REDIRECT": False,
                    },
                    "mappings": [
                        {"internal_field": "username", "external_field": "cas:user"},
                        {"internal_field": "last_name", "external_field": "sn"},
                        {"internal_field": "first_name", "external_field": "givenName"},
                        {"internal_field": "email", "external_field": "mail"},
                    ],
                }
            ],
        },
    ]

    for auth_method_data in auth_methods:
        auth_method_data = auth_method_data.copy()
        configs_data = auth_method_data.pop("configs", [])

        # Create AuthMethod instance
        auth_method, created = AuthMethod.objects.get_or_create(
            name=auth_method_data["name"],
            auth_type=auth_method_data["auth_type"],
            enabled=auth_method_data["enabled"],
            priority=auth_method_data["priority"],
        )

        # Create related AuthConfig instances
        for config_data in configs_data:
            mappings_data = config_data.pop("mappings", [])

            try:
                auth_config, created = AuthConfig.objects.get_or_create(
                    auth_method=auth_method,
                    enabled=config_data["enabled"],
                    priority=config_data["priority"],
                    config=config_data["config"],
                )

            except Exception as e:
                print(f"Error creating AuthConfig: {e}")
                continue

            for mapping_data in mappings_data:
                try:
                    AuthMapping.objects.get_or_create(
                        auth_config=auth_config,
                        internal_field=mapping_data["internal_field"],
                        external_field=mapping_data["external_field"],
                    )
                except Exception as e:
                    print(f"Error creating AuthMapping: {e}")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_field", models.CharField(max_length=255)),
                ("internal_field", models.CharField(max_length=255)),
                (
                    "auth_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="auth_config.authconfig",
                    ),
                ),
            ],
        ),
        migrations.RunPython(add_auth_methods),
    ]
