# Generated by Django 4.2.7 on 2024-07-05 13:52

import django.db.models.deletion
from django.db import migrations, models


def create_osname_rules_with_actions(apps, schema_editor):
    Rule = apps.get_model("rule", "Rule")
    Action = apps.get_model("rule", "Action")

    rules = [
        {
            "description": "Assign Windows template",
            "trigger": "inventory_received",
            "enabled": True,
            "logic": {"regex": [{"var": "osname"}, "(?i)(Windows)"]},
            "actions": [
                {
                    "action": "set",
                    "field": "template",
                    "value": 5,
                    "priority": 1,
                }
            ],
            "priority": 1,
        },
        {
            "description": "Assign Linux (Debian based) template",
            "trigger": "inventory_received",
            "enabled": True,
            "logic": {
                "regex": [
                    {"var": "osname"},
                    "(?i)(Ubuntu|Debian)",
                ]
            },
            "actions": [
                {
                    "action": "set",
                    "field": "template",
                    "value": 2,
                    "priority": 1,
                }
            ],
            "priority": 2,
        },
        {
            "description": "Assign Linux (RHEL based) template",
            "trigger": "inventory_received",
            "enabled": True,
            "logic": {
                "regex": [
                    {"var": "osname"},
                    "(?i)(Redhat|Centos|Alma|Rocky|Fedora)",
                ]
            },
            "actions": [
                {
                    "action": "set",
                    "field": "template",
                    "value": 3,
                    "priority": 1,
                }
            ],
            "priority": 3,
        },
        {
            "description": "Assign Mac template",
            "trigger": "inventory_received",
            "enabled": True,
            "logic": {"regex": [{"var": "osname"}, "(?i)(Mac)"]},
            "actions": [
                {
                    "action": "set",
                    "field": "template",
                    "value": 4,
                    "priority": 1,
                }
            ],
            "priority": 4,
        },
        {
            "description": "Assign Legacy template",
            "trigger": "inventory_received",
            "enabled": True,
            "logic": {"regex": [{"var": "agent"}, "(?i)(OCS-NG)"]},
            "actions": [
                {
                    "action": "set",
                    "field": "template",
                    "value": 1,
                    "priority": 1,
                }
            ],
            "priority": 5,
        },
        {
            "description": "Assign SNMP template",
            "trigger": "inventory_received",
            "enabled": True,
            "logic": {"==": [{"var": "osname"}, "SNMP"], "case_sensitive": False},
            "actions": [
                {
                    "action": "set",
                    "field": "template",
                    "value": 6,
                    "priority": 1,
                }
            ],
            "priority": 6,
        },
    ]

    # create rules and associated actions
    for rule in rules:
        try:
            new_rule = Rule.objects.create(
                description=rule["description"],
                trigger=rule["trigger"],
                enabled=rule["enabled"],
                logic=rule["logic"],
                priority=rule["priority"],
                break_on_match=False,
            )

            for action in rule["actions"]:
                Action.objects.create(
                    rule=new_rule,
                    action=action["action"],
                    field=action["field"],
                    value=action["value"],
                    priority=action["priority"],
                )
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("inventory_received", "Inventory Received"),
                            ("user_login", "User Login"),
                            ("netdevice_received", "Netdevice Received"),
                        ],
                        max_length=50,
                    ),
                ),
                ("priority", models.IntegerField()),
                ("break_on_match", models.BooleanField(default=False)),
                ("logic", models.JSONField()),
                ("enabled", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(choices=[("set", "Set")], max_length=50)),
                ("priority", models.IntegerField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("object_slug", models.CharField(max_length=100, null=True)),
                ("field", models.CharField(max_length=255)),
                ("value", models.JSONField()),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="rule.rule",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_osname_rules_with_actions),
    ]
