# Generated by Django 6.0.6 on 2026-06-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rule", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["rule", "priority"]},
        ),
        migrations.AlterModelOptions(
            name="rule",
            options={"ordering": ["trigger", "priority"]},
        ),
    ]
