# Generated by Django 4.2.3 on 2024-01-02 09:39

from django.db import migrations, models


def create_base_config(apps, schema_editor):
    configs = [
        {
            "name": "agent",
            "value": [
                {
                    "name": "debug",
                    "description": "Enable debug mode",
                    "value": 0,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "frequency",
                    "description": "Frequency of inventory in hours",
                    "value": 24,
                    "type": "number input",
                    "unit": "hours",
                },
                {
                    "name": "inventory_datafilter",
                    "description": "Update inventory using the CHECKSUM agent value",
                    "value": 0,
                    "type": "switch",
                    "unit": "",
                },
            ],
        },
        {
            "name": "server",
            "value": [
                {
                    "name": "debug",
                    "description": "Enable debug mode",
                    "value": 0,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "frequency",
                    "description": "Frequency of inventory in hours",
                    "value": 24,
                    "type": "number input",
                    "unit": "hours",
                },
                {
                    "name": "inventory_checksum",
                    "description": "Enable differential update of inventory",
                    "value": 1,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "duplicate_reconciliation",
                    "description": "Field used to reconcile duplicate computers",
                    "value": "",
                    "type": "select",
                    "unit": "",
                    "options": ["name", "uuid", "srcmac"],
                },
            ],
        },
        {
            "name": "networkscan",
            "value": [
                [
                    {
                        "name": "ipdiscover",
                        "description": "Enable ipdiscover",
                        "value": 0,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "scantype",
                        "description": "Type of scan",
                        "value": "nmap",
                        "type": "select",
                        "unit": "",
                        "options": ["nmap", "ping"],
                    },
                    {
                        "name": "bandwidth",
                        "description": "Bandwidth of the ARP scan",
                        "value": 1000,
                        "type": "number input",
                        "unit": "kb/s",
                    },
                ],
                [
                    {
                        "name": "snmp",
                        "description": "Enable snmp",
                        "value": 0,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "snmp_configs",
                        "description": "List of snmp configs",
                        "value": "",
                        "type": "text input",
                        "unit": "",
                    },
                ],
            ],
        },
        {
            "name": "blacklist",
            "value": [
                [
                    {
                        "name": "macaddresses",
                        "description": "Enable macaddresses blacklist",
                        "value": 0,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "macaddresses_list",
                        "description": "List of macaddresses to blacklist",
                        "value": "",
                        "type": "text input",
                        "unit": "",
                    },
                ],
                [
                    {
                        "name": "ipaddresses",
                        "description": "Enable ipaddresses blacklist",
                        "value": 0,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "ipaddresses_list",
                        "description": "List of ipaddresses to blacklist",
                        "value": "",
                        "type": "text input",
                        "unit": "",
                    },
                ],
                [
                    {
                        "name": "serialnumbers",
                        "description": "Enabble serialnumbers blacklist",
                        "value": 0,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "serialnumbers_list",
                        "description": "List of serialnumbers to blacklist",
                        "value": "",
                        "type": "text input",
                        "unit": "",
                    },
                ],
            ],
        },
        {
            "name": "deployment",
            "value": [
                {
                    "name": "enabled",
                    "description": "Enable deployment",
                    "value": 0,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "period_latency",
                    "description": "Period of latency between packages in seconds",
                    "value": 60,
                    "type": "number input",
                    "unit": "seconds",
                },
                {
                    "name": "auto_retry",
                    "description": "Enable auto retry if deployment failed",
                    "value": 0,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "max_retry",
                    "description": "Max retry number for a package to retry",
                    "value": 3,
                    "type": "number input",
                    "unit": "",
                },
                {
                    "name": "execution_timeout",
                    "description": "Timeout of command execution in seconds",
                    "value": 300,
                    "type": "number input",
                    "unit": "seconds",
                },
            ],
        },
    ]

    Config = apps.get_model("config", "Config")

    for config in configs:
        try:
            Config.objects.create(**config)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
            ],
        ),
        migrations.RunPython(create_base_config),
    ]
