# Generated by Django 4.2.3 on 2024-01-02 09:39

from django.db import migrations, models


def create_base_config(apps, schema_editor):
    configs = [
        {
            "name": "agent",
            "value": [
                {
                    "name": "frequency",
                    "description": "Frequency of inventory in hours",
                    "value": 4,
                    "type": "number input",
                    "unit": "hours",
                },
                {
                    "name": "inventory_checksum",
                    "description": "Enable differential update of inventory",
                    "value": True,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "inventory_loglevel",
                    "description": "Inventory log level (server)",
                    "value": "ERROR",
                    "type": "select",
                    "unit": "",
                    "options": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                },
            ],
        },
        {
            "name": "server",
            "value": [
                {
                    "name": "log_level_collection",
                    "description": "Inventory collection log level",
                    "value": "INFO",
                    "type": "select",
                    "unit": "",
                    "options": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                },
                {
                    "name": "log_level_backend",
                    "description": "OCS backend application log level",
                    "value": "INFO",
                    "type": "select",
                    "unit": "",
                    "options": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                },
                {
                    "name": "log_level_django",
                    "description": "Django backend log level",
                    "value": "INFO",
                    "type": "select",
                    "unit": "",
                    "options": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                },
                {
                    "name": "log_level_management",
                    "description": "OCS management commands log level",
                    "value": "INFO",
                    "type": "select",
                    "unit": "",
                    "options": ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                },
                {
                    "name": "duplicate_reconciliation",
                    "description": "Field used to reconcile duplicate computers",
                    "value": "uuid",
                    "type": "select",
                    "unit": "",
                    "options": ["uuid", "uuid, name", "uuid, srcmac"],
                },
                {
                    "name": "accountinfo_generation",
                    "description": "Mode of administrative data generation",
                    "value": "agent",
                    "type": "select",
                    "unit": "",
                    "options": ["agent", "automation"],
                },
                {
                    "name": "purge_agent_log",
                    "description": "Enable log agent purge",
                    "value": False,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "purge_agent_log_interval",
                    "description": "Interval in days for purging agent logs",
                    "value": 30,
                    "type": "number input",
                    "unit": "days",
                },
                {
                    "name": "purge_deployment_package",
                    "description": "Enable deployment package purge",
                    "value": False,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "purge_deployment_package_max_age",
                    "description": "Interval in months for purging deployment packages",
                    "value": 3,
                    "type": "number input",
                    "unit": "months",
                },

            ],
        },
        {
            "name": "ipdiscover",
            "value": [
                [
                    {
                        "name": "ipdiscover",
                        "description": "Enable ipdiscover",
                        "value": False,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "scantype",
                        "description": "Type of scan",
                        "value": "nmap",
                        "type": "select",
                        "unit": "",
                        "options": ["nmap", "ping"],
                    },
                    {
                        "name": "bandwidth",
                        "description": "Bandwidth of the ARP scan",
                        "value": 1000,
                        "type": "number input",
                        "unit": "kb/s",
                    },
                ],
            ],
        },
        {
            "name": "snmp",
            "value": [
                {
                    "name": "snmp",
                    "description": "Enable snmp",
                    "value": False,
                    "type": "switch",
                    "unit": "",
                }
            ],
        },
        {
            "name": "blacklist",
            "value": [
                [
                    {
                        "name": "macaddresses",
                        "description": "Enable macaddresses blacklist",
                        "value": False,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "macaddresses_list",
                        "description": "List of macaddresses to blacklist, separated by commas",
                        "value": "",
                        "type": "text input",
                        "unit": "",
                    },
                ],
                [
                    {
                        "name": "ipaddresses",
                        "description": "Enable subnets blacklist",
                        "value": False,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "ipaddresses_list",
                        "description": "List of subnets to blacklist in CIDR notation, separated by commas",
                        "value": "",
                        "type": "text input",
                        "unit": "",
                    },
                ],
                [
                    {
                        "name": "serialnumbers",
                        "description": "Enable serialnumbers blacklist",
                        "value": False,
                        "type": "switch",
                        "unit": "",
                    },
                    {
                        "name": "serialnumbers_list",
                        "description": "List of serialnumbers to blacklist, separated by commas",
                        "value": "",
                        "type": "text input",
                        "unit": "",
                    },
                ],
            ],
        },
        {
            "name": "deployment",
            "value": [
                {
                    "name": "enabled",
                    "description": "Enable deployment",
                    "value": False,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "period_latency",
                    "description": "Period of latency between packages in seconds",
                    "value": 60,
                    "type": "number input",
                    "unit": "seconds",
                },
                {
                    "name": "auto_retry",
                    "description": "Enable auto retry if deployment failed",
                    "value": False,
                    "type": "switch",
                    "unit": "",
                },
                {
                    "name": "max_retry",
                    "description": "Max retry number for a package to retry",
                    "value": 3,
                    "type": "number input",
                    "unit": "",
                },
                {
                    "name": "execution_timeout",
                    "description": "Timeout of command execution in seconds",
                    "value": 300,
                    "type": "number input",
                    "unit": "seconds",
                },
                {
                    "name": "deployment_timeout",
                    "description": "Timeout of deployment in seconds",
                    "value": 240,
                    "type": "number input",
                    "unit": "seconds",
                },
            ],
        },
    ]

    Config = apps.get_model("config", "Config")

    for config in configs:
        try:
            Config.objects.create(**config)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
            ],
        ),
        migrations.RunPython(create_base_config),
    ]
