# Generated by Django 6.0.6 on 2026-06-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['name']},
        ),
    ]
