# Generated by Django 4.2.7 on 2025-04-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['name']},
        ),
    ]
