# Generated by Django 3.1.7 on 2021-05-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="config",
            old_name="vaue",
            new_name="value",
        ),
    ]
