# Generated by Django 4.2.7 on 2025-04-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0002_alter_template_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('osname', models.CharField(max_length=255)),
                ('osversion', models.CharField(blank=True, max_length=255)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('srcip', models.CharField(blank=True, max_length=255)),
                ('srcmac', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='template.template')),
            ],
        ),
    ]
