# Generated by Django 6.1.1 on 2026-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybase",
            name="testtest",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
