# Generated by Django 4.2.4 on 2023-08-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetId', models.TextField(max_length=255, null=True)),
                ('sectionName', models.TextField(max_length=255, null=True)),
                ('sectionJson', models.JSONField(null=True)),
                ('sectionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='inventory.inventory')),
            ],
        ),
    ]
