# Generated by Django 6.0.6 on 2026-06-05 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_group', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroup',
            name='assets',
            field=models.ManyToManyField(blank=True, to='inventory_base.inventorybase'),
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
