# Generated by Django 3.2 on 2021-05-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('retrival_method', models.CharField(choices=[('FILE', 'Read file'), ('BASH', 'Bash command'), ('PW', 'Powershell command'), ('CMD', 'Cmd command')], default='FILE', max_length=4)),
                ('target', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template')),
            ],
        ),
    ]
