# Generated by Django 5.0.6 on 2024-05-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "retrieval_method",
                    models.CharField(
                        choices=[
                            ("FILE", "Read file"),
                            ("BASH", "Bash command"),
                            ("PW", "Powershell command"),
                            ("CMD", "Cmd command"),
                        ],
                        default="FILE",
                        max_length=4,
                    ),
                ),
                (
                    "retrieval_output",
                    models.CharField(
                        choices=[
                            ("PTXT", "Plain text"),
                            ("JSON", "JSON format"),
                            ("TBLE", "Table format"),
                            ("REGX", "Regex processing"),
                            ("GREP", "Grep command output"),
                        ],
                        default="JSON",
                        max_length=4,
                    ),
                ),
                ("target", models.TextField()),
                ("options", models.JSONField(null=True)),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="template.template",
                    ),
                ),
            ],
        ),
    ]
