# Generated by Django 3.2 on 2021-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='retrival_output',
            field=models.CharField(choices=[('PTXT', 'Plain text'), ('JSON', 'JSON format'), ('TBLE', 'Table format')], default='JSON', max_length=4),
        ),
    ]
