# Generated by Django 4.2.7 on 2025-04-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='retrival_method',
            field=models.CharField(choices=[('FILE', 'Read file'), ('BASH', 'Bash command'), ('PW', 'Powershell command'), ('CMD', 'Cmd command'), ('SNMP_WALK', 'Walk the SNMP tree starting from a specific OID'), ('SNMP_GET', 'Get a specific OID')], default='FILE', max_length=10),
        ),
    ]
