# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_default_legacy_sections(apps, schema_editor):
    sections = [
        {
            "name": "ACCOUNTINFO",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "BATTERIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "BIOS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "CONTROLLERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "CPUS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "DRIVES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "HARDWARE",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "INPUTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "LOCAL_GROUPS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "LOCAL_USERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "MEMORIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "MODEMS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "MONITORS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "NETWORKS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "PORTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "PRINTERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "REPOSITORY",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "SLOTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "SOFTWARES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "SOUNDS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "STORAGES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "USBDEVICES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "VIDEOS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
        {
            "name": "VIRTUALMACHINES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {},
            "template": apps.get_model("template", "Template").objects.get(os="LEG"),
        },
    ]

    Section = apps.get_model("section", "Section")

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_legacy_sections),
    ]
