# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_default_linux_sections(apps, schema_editor):
    os_types = ["RHEL", "DEB"]

    sections = [
        {
            "name": "BATTERIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "upower -i $(upower -e | grep BAT)",
            "options": {"separator": "native-path:", "multiple": False},
        },
        {
            "name": "BIOS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "dmidecode",
            "options": {"separator": None, "multiple": False},
        },
        {
            "name": "CONTROLLERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lspci -nnvmm",
            "options": {"separator": "Slot:", "multiple": False},
        },
        {
            "name": "CPUS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "LANG=C lscpu && dmidecode -t processor",
            "options": {"separator": None, "multiple": False},
        },
        {
            "name": "DRIVES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "df -TP | awk 'NR==1{next} {printf \"Filesystem: %s\\nType: %s\\n1K-blocks: %s\\nAvailable: %s\\nUse%%: %s\\nMounted: %s\\nSize_MB: %.2f\\nAvail_MB: %.2f\\n---\\n\", $1, $2, $3, $5, $6, $7, $3/1024, $5/1024}'",
            "options": {"separator": "---", "multiple": False},
        },
        {
            "name": "INPUTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": 'awk -v RS=\'\' \'{ if(match($0,/Bus=[0-9a-fA-F]+/)){ bus_val=substr($0,RSTART,RLENGTH); sub(/Bus=/,"",bus_val); }else{ bus_val=""; } if(match($0,/Vendor=[0-9a-fA-F]+/)){ vendor_val=substr($0,RSTART,RLENGTH); sub(/Vendor=/,"",vendor_val); }else{ vendor_val=""; } if(match($0,/Product=[0-9a-fA-F]+/)){ product_val=substr($0,RSTART,RLENGTH); sub(/Product=/,"",product_val); }else{ product_val=""; } if(match($0,/Name="[^"]+"/)){ name_val=substr($0,RSTART,RLENGTH); sub(/Name="/,"",name_val); sub(/"$/,"",name_val); }else{ name_val=""; } if(match($0,/Sysfs=[^ \\n]+/)){ sysfs_val=substr($0,RSTART,RLENGTH); sub(/Sysfs=/,"",sysfs_val); }else{ sysfs_val=""; } b_clean=toupper(bus_val); sub(/^0+/,"",b_clean); if(b_clean=="")b_clean="0"; bus_hex=(length(b_clean)==1?"0x0" b_clean:"0x" b_clean); bus=(bus_hex=="0x01")?"PCI":(bus_hex=="0x02")?"ISAPNP":(bus_hex=="0x03")?"USB":(bus_hex=="0x04")?"HIL":(bus_hex=="0x05")?"Bluetooth":(bus_hex=="0x06")?"Virtual":(bus_hex=="0x10")?"ISA":(bus_hex=="0x11")?"i8042":(bus_hex=="0x12")?"XT Keyboard":(bus_hex=="0x13")?"RS232":(bus_hex=="0x14")?"Gameport":(bus_hex=="0x15")?"Parallel Port":(bus_hex=="0x16")?"Amiga":(bus_hex=="0x17")?"ADB (Apple Desktop Bus)":(bus_hex=="0x18")?"I2C":(bus_hex=="0x19")?"Host":(bus_hex=="0x1A")?"GSC":(bus_hex=="0x1B")?"Atari":(bus_hex=="0x1C")?"SPI":(bus_hex=="0x1D")?"RMI":(bus_hex=="0x1E")?"CEC":(bus_hex=="0x1F")?"Intel ISHTP":(bus_hex=="0x20")?"AMD SFH":"Unknown (" bus_hex ")"; print "Type: " bus; print "Bus: " bus_val; vendor=tolower(vendor_val); print "Vendor: " vendor; product=tolower(product_val); print "Product: " product; if(vendor!=""){ cmd="cat /usr/share/hwdata/usb.ids /var/lib/usbutils/usb.ids /usr/share/misc/usb.ids 2>/dev/null | grep -i \\x27^" vendor " \\x27 | head -n1 | cut -c7-"; manufacturer=""; cmd | getline manufacturer; close(cmd); print "Manufacturer: " manufacturer; if(product!=""){ cmd2="cat /usr/share/hwdata/usb.ids /var/lib/usbutils/usb.ids /usr/share/misc/usb.ids 2>/dev/null | awk \\x27/^" vendor " /{flag=1; next} /^[^[:space:]]/{flag=0} flag && /^[[:space:]]+" product " /{print substr($0, index($0, \\x27" product "\\x27) + 5); exit}\\x27"; description=""; cmd2 | getline description; close(cmd2); print "Description: " description; } if(name_val!="")print "Caption: " name_val; if(sysfs_val!="")print "Interface: " sysfs_val; print "---"; } }\' /proc/bus/input/devices',
            "options": {"separator": "---", "multiple": False},
        },
        {
            "name": "LOCAL GROUPS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "cat /etc/group",
            "options": {"separator": None, "multiple": True},
        },
        {
            "name": "LOCAL USERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "cat /etc/passwd",
            "options": {"serparator": None, "multiple": True},
        },
        {
            "name": "MEMORIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "dmidecode -t 17 -q",
            "options": {"separator": "Memory Device", "multiple": False},
        },
        {
            "name": "MONITORS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": 'for f in /sys/class/drm/*/edid; do [ -f "$f" ] || continue; echo "Screen: $(basename "$(dirname "$f")")"; cat "$f" | parse-edid 2>&1 | sed -nE \'s/.*week ([0-9]+) of ([0-9]+).*/Manufactured week\/year: \\1\/\\2/p; t; p\'; serial=$(hexdump -v -e \'1/1 "%02x"\' "$f" | cut -c25-32); [ -n "$serial" ] && echo "Serial number: $((0x$serial))"; echo "---"; done',
            "options": {"separator": "---", "multiple": False},
        },
        {
            "name": "PORTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "dmidecode -t connector",
            "options": {"separator": None, "multiple": True},
        },
        {
            "name": "PRINTERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": 'for name in $(lpstat -p 2>/dev/null | awk \'{print $2}\'); do description=$(lpstat -l -p "$name" | grep "Description" | cut -d: -f2- | sed \'s/^ *//\'); port=$(lpstat -v "$name" | awk -F\': \' \'{print $2}\'); driver=$(lpoptions -p "$name" | grep "printer-make-and-model" | cut -d"\'" -f2); echo "Name: $name"; echo "Description: $description"; echo "Port: $port"; echo "Driver: $driver"; echo "---"; done',
            "options": {"separator": "---", "multiple": False},
        },
        {
            "name": "SLOTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "dmidecode -t slot",
            "options": {"separator": "System Slot Information", "multiple": False},
        },
        {
            "name": "SOUNDS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lspci -nn | grep -i audio | cut -d ' ' -f1 | xargs -I{} lspci -vmm -s {}",
            "options": {"separator": "Slot:", "multiple": False},
        },
        {
            "name": "STORAGES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": 'for storage in $(lsblk -dno NAME,TYPE | awk \'$2=="disk"{print $1}\'); do echo "Name: $storage"; read type size rota tran < <(lsblk -dnro TYPE,SIZE,ROTA,TRAN "/dev/$storage"); rota_int=$(echo "$rota" | tr -d "[:space:]"); description="$([ $rota_int -eq 0 ] && echo SSD || echo HDD) - $tran"; echo -e "Type: $type\\nDiskSize: $size\\nDescription: $description"; smartctl_info=$(smartctl -i "/dev/$storage" 2>/dev/null); echo "$smartctl_info" | grep -E "Model Number|Serial Number|Firmware Version" | sed -e \'s/Model Number:/Model:/\' -e \'s/Serial Number:/SerialNumber:/\' -e \'s/Firmware Version:/Firmware:/\'; pci_line=$(echo "$smartctl_info" | grep "PCI Vendor/Subsystem ID"); if [[ -n "$pci_line" ]]; then pci_id=$(echo "$pci_line" | grep -Po \'0x[0-9a-fA-F]+\'); vendor_id=${pci_id#0x}; if [[ -f /usr/share/hwdata/pci.ids ]]; then manufacturer=$(grep -i "^$vendor_id " /usr/share/hwdata/pci.ids | head -n1 | cut -f2- -d\' \'); echo "Manufacturer: $manufacturer"; fi; fi; echo "---"; done',
            "options": {"separator": "---", "multiple": False},
        },
        {
            "name": "USB DEVICES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lsusb -v",
            "options": {"separator": "\\nBus", "multiple": False},
        },
        {
            "name": "VIDEOS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": 'videos=($(lspci | grep -iE \'graphics|vga|video|display\' | cut -d \' \' -f1)); for slot in "${videos[@]}"; do info=$(lspci -vmm -s "$slot"); chipset=$(echo "$info" | grep \'^Class:\' | cut -f2-); vendor=$(echo "$info" | grep \'^Vendor:\' | cut -f2-); device=$(echo "$info" | grep \'^Device:\' | cut -f2-); name="$vendor $device"; memory=0; while IFS= read -r line; do if [[ $line =~ Memory.*\\(.*-bit,\\ prefetchable\\)\\ \\[size=([0-9]+)([GMK])\\] ]]; then size=${BASH_REMATCH[1]}; unit=${BASH_REMATCH[2]}; case $unit in G) bytes=$(( size * 1024 * 1024 * 1024 )) ;; M) bytes=$(( size * 1024 * 1024 )) ;; K) bytes=$(( size * 1024 )) ;; esac; memory=$(( memory + bytes )); fi; done < <(lspci -v -s "$slot" 2>/dev/null); memory_mb=$(( (memory + 524288) / 1048576 )); echo "Chipset: $chipset"; echo "Name: $name"; echo "Memory: ${memory_mb} MB"; echo "---"; done',
            "options": {"separator": "---", "multiple": False},
        },
        {
            "name": "VIRTUAL MACHINES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "(for u in $(cut -d: -f1 /etc/passwd); do sudo -u $u bash -c 'VBoxManage list vms; virsh --connect qemu:///session list --all --name'; done; virsh --connect qemu:///system list --all --name) 2>/dev/null | grep -v '^$'",
            "options": {"separator": None, "multiple": True},
        },
    ]

    Template = apps.get_model("template", "Template")
    Section = apps.get_model("section", "Section")

    for os_type in os_types:
        try:
            template = Template.objects.get(os=os_type)
        except Exception as e:
            print(e)
            continue
        for section in sections:
            section_data = section.copy()
            section_data["template"] = template
            try:
                Section.objects.create(**section_data)
            except Exception as e:
                print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0002_legacy"),
    ]

    operations = [
        migrations.RunPython(create_default_linux_sections),
    ]
