# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_default_linux_sections(apps, schema_editor):
    sections = [
        {
            "name": "ACCOUNT INFO",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "who",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {},
        },
        {
            "name": "BATTERIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "upower -i $(upower -e | grep BAT)",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {},
        },
        {
            "name": "BIOS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo dmidecode -t bios -t baseboard -t chassis | grep -Ei 'vendor|version|release date|serial number|product name|type'",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {},
        },
        {
            "name": "CONTROLLERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lspci -nn",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "CPUS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "LANG=C lscpu",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {},
        },
        {
            "name": "DRIVES",
            "retrieval_method": "BASH",
            "retrieval_output": "TBLE",
            "target": "lsblk -o NAME,FSTYPE,SERIAL,MODEL,VENDOR,SIZE,MOUNTPOINTS,TYPE",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"use_index": False},
        },
        {
            "name": "HARDWARE",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": 'for f in system-manufacturer system-product-name system-serial-number chassis-type baseboard-manufacturer baseboard-product-name baseboard-serial-number bios-vendor bios-version; do echo -n "$f: "; dmidecode -s $f; done',
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {},
        },
        {
            "name": "INPUTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "cat /proc/bus/input/devices",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": False, "separator": "I:"},
        },
        {
            "name": "LOCAL GROUPS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "cat /etc/group",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "LOCAL USERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "cat /etc/passwd",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "MEMORIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo dmidecode -t 17 -q",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": False, "separator": "Memory Device"},
        },
        {
            "name": "MODEMS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "/sbin/ifconfig -a",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": False, "separator": "collisions"},
        },
        {
            "name": "MONITORS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": """for f in /sys/class/drm/*/edid; do [ -f "$f" ] && echo "Screen: $(basename $(dirname "$f"))" && sudo cat "$f" | parse-edid && serial=$(sudo hexdump -v -e '1/1 "%02x"' "$f" | cut -c25-32) && [ -n "$serial" ] && echo "Serial number: $((0x$serial))"; done""",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": False, "separator": "Screen"},
        },
        {
            "name": "NETWORKS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "nmcli connection show",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "PORTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lsusb",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "PRINTERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo lpstat -l -e -t",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": False, "separator": "Default port settings:"},
        },
        {
            "name": "REPOSITORY",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "apt list --installed",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "SLOTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lspci | grep -i 'pci'",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "SOFTWARES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "dpkg-query --list | tail -n +6",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "SOUNDS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lspci",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "STORAGES",
            "retrieval_method": "BASH",
            "retrieval_output": "TBLE",
            "target": "df -TP",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"use_index": False},
        },
        {
            "name": "USB DEVICES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lsusb",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "VIDEOS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": """lspci|grep -i vga;for d in $(lspci|awk '/vga/{print $1}');do lspci -v -s $d|grep 'Kernel';done;f=/sys/class/drm/card0/device/mem_info_vram_total;[ -f $f ]&&echo $(( $(cat $f)/1048576 ))MB;xrandr|grep '*'""",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {},
        },
        {
            "name": "VIRTUAL MACHINES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "hostnamectl",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {},
        },
    ]

    Section = apps.get_model("section", "Section")

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0002_legacy"),
    ]

    operations = [
        migrations.RunPython(create_default_linux_sections),
    ]
