# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_default_linux_sections(apps, schema_editor):
    sections = [
        {
            "name": "AUDIO",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lspci",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "BATTERIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo dmidecode -t 22 -q",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": None,
        },
        {
            "name": "CONTROLLERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lspci -nn",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "CPUS",
            "retrieval_method": "BASH",
            "retrieval_output": "JSON",
            "target": "lscpu",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": None,
        },
        {
            "name": "CURRENT_USER",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "who",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": None,
        },
        {
            "name": "ETHERNET",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "/sbin/ifconfig -a",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True, "separator": "collisions \\d"},
        },
        {
            "name": "GRAPHIC/DISPLAY",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo lshw -class display",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True, "separator": ".*display"},
        },
        {
            "name": "GROUPS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "cat /etc/group",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "HARDWARE",
            "retrieval_method": "BASH",
            "retrieval_output": "PTXT",
            "target": "echo BIOS",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": None,
        },
        {
            "name": "INPUTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "cat /proc/bus/input/devices",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True, "separator": "^$"},
        },
        {
            "name": "MEMORIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo dmidecode -t 17 -q",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True, "separator": "^$"},
        },
        {
            "name": "NETWORKS",
            "retrieval_method": "BASH",
            "retrieval_output": "PTXT",
            "target": "echo HARDWARE",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": None,
        },
        {
            "name": "OPERATING_SYSTEM",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "hostnamectl",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True, "separator": "Hardware Model:.*"},
        },
        {
            "name": "PACKAGES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "apt-cache policy",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "PORTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo dmidecode -t 8 -q",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True, "separator": "^$"},
        },
        {
            "name": "PRINTERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo lpstat -l -e",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "SLOTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "sudo dmidecode -t 9 -q",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True, "separator": "^$"},
        },
        {
            "name": "SOFTWARES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "dpkg-query --show --showformat=\\'\\${binary:Package}---\\${Architecture}---\\${Version}---\\${Installed-Size}---\\${Homepage}\\n\\'",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "STORAGES",
            "retrieval_method": "BASH",
            "retrieval_output": "TBLE",
            "target": "df -TP",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"use_index": False},
        },
        {
            "name": "USB",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "lsusb",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "USERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "cat /etc/passwd",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
        {
            "name": "WI_FI",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "nmcli connection show",
            "template": apps.get_model("template", "Template").objects.get(os="LIN"),
            "options": {"multiple": True},
        },
    ]

    Section = apps.get_model("section", "Section")

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0002_legacy"),
    ]

    operations = [
        migrations.RunPython(create_default_linux_sections),
    ]
