# Generated by Django 3.2 on 2021-10-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0001_initial"),
        ("section", "0003_alter_section_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="template.template",
            ),
        ),
    ]
