# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_default_macos_sections(apps, schema_editor):
    sections = [
        {
            "name": "AUDIO",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPAudioDataType -json",
            "options": {"submap": "_items"},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "BATTERIES",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPPowerDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "BLUETOOTH",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPBluetoothDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "CAMERAS",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPCameraDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "CONTROLLERS",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPiBridgeDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "CPUS",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPHardwareDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "CURRENT_USER",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPSoftwareDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "DEVELOPER_TOOLS",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPDeveloperToolsDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "ETHERNET",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPEthernetDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "EXTENSIONS",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPExtensionsDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "FRAMEWORKS",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPFrameworksDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "GRAPHIC/DISPLAY",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPDisplaysDataType",
            "options": {"multiple": False, "separator": "Rotation:\\s(.*)"},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "GROUPS",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "dscl . readall /groups",
            "options": {"multiple": False, "separator": "-"},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "HARDWARE",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPHardwareDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "MEMORIES",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPMemoryDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "NETWORKS",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPNetworkDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "NVME",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPNVMeDataType -json",
            "options": {"submap": "_items"},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "OPERATING_SYSTEM",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPSoftwareDataType",
            "options": {"multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "PRINTERS",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPPrintersDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "SLOTS",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPNetworkVolumeDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "SOFTWARES",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPApplicationsDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "STORAGES",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPStorageDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "USB",
            "retrival_method": "BASH",
            "retrival_output": "JSON",
            "target": "system_profiler SPUSBDataType -json",
            "options": None,
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "USERS",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "dscl . readall /groups",
            "options": {"multiple": False, "separator": "-"},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
        {
            "name": "WI_FI",
            "retrival_method": "BASH",
            "retrival_output": "REGX",
            "target": "system_profiler SPAirPortDataType",
            "options": {"multiple": False, "separator": "Security:\\s(.*)"},
            "template": apps.get_model("template", "Template").objects.get(os="MAC"),
        },
    ]

    Section = apps.get_model("section", "Section")

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0003_linux"),
    ]

    operations = [
        migrations.RunPython(create_default_macos_sections),
    ]
