# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_default_windows_sections(apps, schema_editor):
    sections = [
        {
            "name": "AUDIO",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -Class Win32_SoundDevice | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "BATTERIES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_PortableBattery -Property * | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "CONTROLLERS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -Class Win32_ComputerSystem | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "CPUS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_Processor -Property * | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "CURRENT USER",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -Class Win32_UserAccount -Property * | Where-Object { $_.Name -eq $env:USERNAME } | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "ETHERNET",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": 'Get-NetAdapter -Name "*Ethernet*" | ConvertTo-Json',
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "GRAPHIC/DISPLAY",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -Class Win32_VideoController | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "GROUPS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_Group -Property * | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "HARDWARE",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_SystemEnclosure -Property * | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "INPUTS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -className Win32_PnpEntity -Property * | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "MEMORIES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_PhysicalMemory -Property * | ForEach-Object { $_.Capacity = [math]::round($_.Capacity / 1GB, 2); $_ } | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "NETWORKS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_NetworkAdapterConfiguration -property * -Filter IPEnabled=$True | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "OPERATING SYSTEM",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_OperatingSystem -Property * | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "PRINTERS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -Class Win32_Printer | Select-Object Name, PortName, DriverName, Shared | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "SLOTS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -className Win32_SystemSlot -Property * | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "SOFTWARES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-ItemProperty HKLM:\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\* | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "STORAGES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_LogicalDisk -Property * | ForEach-Object { $_.FreeSpace = [math]::round($_.FreeSpace / 1GB, 2); $_.Size = [math]::round($_.Size / 1GB, 2); $_ } | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "USB",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -Class Win32_USBControllerDevice | ForEach-Object { $usbDevice = [WMI]$_; $usbDevice.GetRelated('Win32_PnPEntity') | Select-Object Name, Description, DeviceID } | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "USERS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject -ClassName Win32_UserAccount -Property * | ConvertTo-Json",
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
        {
            "name": "WIFI",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": 'Get-NetAdapter -Name "*Wi-Fi*" | ConvertTo-Json',
            "options": {"need_format": False},
            "template": apps.get_model("template", "Template").objects.get(os="WIN"),
        },
    ]

    Section = apps.get_model("section", "Section")

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0004_macos"),
    ]

    operations = [
        migrations.RunPython(create_default_windows_sections),
    ]
