# Generated by Django 4.2.4 on 2023-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_alter_section_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='options',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='retrival_output',
            field=models.CharField(choices=[('PTXT', 'Plain text'), ('JSON', 'JSON format'), ('TBLE', 'Table format'), ('REGX', 'Regex processing'), ('GREP', 'Grep command output')], default='JSON', max_length=4),
        ),
    ]
