# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_redhat_linux_sections(apps, schema_editor):
    sections = [
        {
            "name": "REPOSITORY",
            "retrieval_method": "BASH",
            "retrieval_output": "JSON",
            "target": 'LANG=C dnf repoinfo -q | awk \'BEGIN { print "[" } /^Repo.*(id|ID)/ { if (c) print " },"; c=1; sub(/^[^:]+[: \\t]+/, ""); sub(/^[ \\t]+/, ""); printf " { \\"id\\": \\"%s\\", ",$0} /^(Repo-name|Name) /{sub(/^[^:]+[: \\t]+/, ""); sub(/^[ \\t]+/, ""); printf "\\"name\\": \\"%s\\", ",$0} /^(Repo-baseurl|\\s*Base URL) /{sub(/^[^:]+[: \\t]+/, ""); sub(/^[ \\t]+/, ""); printf "\\"base_url\\": \\"%s\\"",$0} END { if (c) print " }"; print "]" }\'',
            "options": {"submap": None},
            "template": apps.get_model("template", "Template").objects.get(os="RHEL"),
        },
        {
            "name": "SOFTWARES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": 'rpm -qa --qf \'%{NAME}\\n\' | while read -r pkg; do rpm -qi "$pkg" | awk -v from="rpm" \'/^Name/ {name=substr($0,index($0,":")+2)} /^Vendor/ {publisher=substr($0,index($0,":")+2)} /^Version/ {version=substr($0,index($0,":")+2)} /^Release/ {release=substr($0,index($0,":")+2); full_version=version"-"release} /^Summary/ {comments=substr($0,index($0,":")+2)} /^Size/ {size=substr($0,index($0,":")+2)} /^InstallDate/ {install_date=substr($0,index($0,":")+2)} /^Architecture/ {arch=substr($0,index($0,":")+2)} END {split(version,vparts,"."); major=vparts[1]; minor=vparts[2]; patch=vparts[3]; printf "Name: %s\\nPublisher: %s\\nVersion: %s\\nComments: %s\\nFileSize: %s\\nInstallDate: %s\\nFrom: %s\\nArchitecture: %s\\nMajor: %s\\nMinor: %s\\nPatch: %s\\n---\\n", name, publisher, full_version, comments, size, install_date, from, arch, major, minor, patch}\'; done',
            "options": {"separator": "---", "multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="RHEL"),
        },
    ]

    Section = apps.get_model("section", "Section")

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0006_snmp"),
    ]

    operations = [
        migrations.RunPython(create_redhat_linux_sections),
    ]
