# Generated by Django 5.0.6 on 2024-05-24 13:53

from django.db import migrations


def create_debian_linux_sections(apps, schema_editor):
    sections = [
        {
            "name": "REPOSITORY",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "apt-cache policy | grep -iE \"http(s)?://\" | awk '{print $2, $3}' | sort -u",
            "options": {"separator": None, "multiple": True},
            "template": apps.get_model("template", "Template").objects.get(os="DEB"),
        },
        {
            "name": "SOFTWARES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": 'dpkg -l | awk \'NR>5 {print $2}\' | while read -r pkg; do install_date=$(stat -c %y "/var/lib/dpkg/info/${pkg}.list" 2>/dev/null | cut -d. -f1 || echo "unknown"); dpkg -s "$pkg" 2>/dev/null | awk -v pkg="$pkg" -v id="$install_date" \'BEGIN {name=pkg;publisher="";version="";comments="";size_kb=0;arch="";from="deb";major="";minor=""} /^Homepage[[:space:]]*:/ {publisher=substr($0,index($0,":")+2)} /^Version[[:space:]]*:/ {version=substr($0,index($0,":")+2); raw_version=version; sub(/^[0-9]+:/, "", raw_version); if(match(raw_version,/^[0-9]+(\\.[0-9]+)*/)){vernum=substr(raw_version,RSTART,RLENGTH); split(vernum, parts, "."); major=(parts[1]~/^[0-9]+$/)?parts[1]:""; if(length(parts)>1) minor=(parts[2]~/^[0-9]+$/)?parts[2]:""; if(length(parts)>2) patch=(parts[3]~/^[0-9]+$/)?parts[3]:"";} } /^Description[[:space:]]*:/ && !d {comments=substr($0,index($0,":")+2); d=1} /^Installed-Size[[:space:]]*:/ {size_kb=substr($0,index($0,":")+2)} /^Architecture[[:space:]]*:/ {arch=substr($0,index($0,":")+2)} END {size=size_kb*1024; printf("Name: %s\\nPublisher: %s\\nVersion: %s\\nComments: %s\\nFileSize: %d\\nInstallDate: %s\\nFrom: %s\\nArchitecture: %s\\n", name, publisher, version, comments, size, id, from, arch); if(major!="") printf("Major: %s\\n", major); if(minor!="") printf("Minor: %s\\n", minor); if(patch!="") printf("Patch: %s\\n", patch); printf("---\\n") }\'; done',
            "options": {"separator": "---", "multiple": False},
            "template": apps.get_model("template", "Template").objects.get(os="DEB"),
        },
    ]

    Section = apps.get_model("section", "Section")

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0007_redhat_linux"),
    ]

    operations = [
        migrations.RunPython(create_debian_linux_sections),
    ]
