# Generated by Django 6.0.6 on 2026-06-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0008_debian_linux"),
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="template.template",
            ),
        ),
    ]
