# Generated for the "Legacy Extended" template

from django.db import migrations


def create_legacy_extended_sections(apps, schema_editor):
    Template = apps.get_model("template", "Template")
    Section = apps.get_model("section", "Section")

    template = Template.objects.get(name="Legacy Extended", os="LEG")

    sections = [
        {
            "name": "ACCOUNTINFO",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "BATTERIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "BIOS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "CONTROLLERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "CPUS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "DRIVES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "HARDWARE",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "INPUTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "LOCAL_GROUPS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "LOCAL_USERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "MEMORIES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "MODEMS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "MONITORS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "NETWORKS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "PORTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "PRINTERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "REPOSITORY",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "SLOTS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "SOFTWARES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "SOUNDS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "STORAGES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "USBDEVICES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "VIDEOS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "VIRTUALMACHINES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False},
            "template": template,
        },
        {
            "name": "ANYDESK",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "DRIVERSLIST",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "POWERSHELLVERSION",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "TEAMVIEWER",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "BITLOCKERSTATUS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "FIREWALLCONFIG",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "SCHEDULEDTASKS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "BROWSEREXTENSIONS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "FIREWALLRULES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "SECURITYCERTIFICATE",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "UWPAPPS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "USERINSTALLEDAPPS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "DEFAULTWINDOWSAPP",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "OSINSTALL",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "SERVICES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "UPTIME",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "WINSECDETAILS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "WINSERVERFEATURES",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "WINUPDATESTATE",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "WINUPDATESCAN",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "WMIPRODUCTLIST",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
        {
            "name": "WINUSERS",
            "retrieval_method": "BASH",
            "retrieval_output": "REGX",
            "target": "None",
            "options": {"multiple": False, "separator": None},
            "template": template,
        },
    ]

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0009_alter_section_template"),
        ("template", "0003_legacy_extended"),
    ]

    operations = [
        migrations.RunPython(create_legacy_extended_sections),
    ]
