from django.db import migrations


def create_windows_extended_sections(apps, schema_editor):
    Template = apps.get_model("template", "Template")
    Section = apps.get_model("section", "Section")

    template = Template.objects.get(name="Windows Extended", os="WIN")

    sections = [
        {
            "name": "DEFAULT WINDOWS APP",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "@((Get-ItemProperty -Path 'HKLM:\\SOFTWARE\\RegisteredApplications').PSObject.Properties | Where-Object { $_.MemberType -eq 'NoteProperty' -and $_.Name -notlike 'PS*' } | ForEach-Object { [PSCustomObject]@{ Name=$_.Name; Type=$_.Value } }) | ConvertTo-Json -Depth 5",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "WIN SERVER FEATURES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WindowsFeature | Where-Object { $_.Installed } | ForEach-Object { [PSCustomObject]@{ Name=$_.Name; DisplayName=$_.DisplayName; Description=$_.Description; Installed=$_.Installed; SubFeatures=$_.SubFeatures } } | ConvertTo-Json -Depth 5",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "BIOS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "[PSCustomObject]@{SystemManufacturer = (Get-CimInstance -ClassName Win32_ComputerSystem).Manufacturer; SystemModel = (Get-CimInstance -ClassName Win32_ComputerSystem).Model; EnclosureSerialNumber = (Get-CimInstance -ClassName Win32_SystemEnclosure).SerialNumber; EnclosureChassisTypes = switch ((Get-CimInstance -ClassName Win32_SystemEnclosure).ChassisTypes) {1 {'Other'}; 2 {'Unknown'}; 3 {'Desktop'}; 4 {'Low Profile Desktop'}; 5 {'Pizza Box'}; 6 {'Mini Tower'}; 7 {'Tower'}; 8 {'Portable'}; 9 {'Laptop'}; 10 {'Notebook'}; 11 {'Hand Held'}; 12 {'Docking Station'}; 13 {'All in One'}; 14 {'Sub Notebook'}; 15 {'Space-Saving'}; 16 {'Lunch Box'}; 17 {'Main System Chassis'}; 18 {'Expansion Chassis'}; 19 {'SubChassis'}; 20 {'Bus Expansion Chassis'}; 21 {'Peripheral Chassis'}; 22 {'Storage Chassis'}; 23 {'Rack Mount Chassis'}; 24 {'Sealed-Case PC'}; 30 {'Tablet'}; 31 {'Convertible'}; 32 {'Detachable'}}; BiosManufacturer = (Get-CimInstance -ClassName Win32_Bios).Manufacturer; BiosVersion = (Get-CimInstance -ClassName Win32_Bios).SMBIOSBIOSVersion; BiosReleaseDate = (Get-CimInstance -ClassName Win32_Bios).ReleaseDate.ToString('dd/MM/yyyy HH:mm:ss'); BBoardManufacturer = (Get-CimInstance -ClassName Win32_BaseBoard).Manufacturer; BBoardModel = (Get-CimInstance -ClassName Win32_BaseBoard).Model; BBoardSerialNumber = (Get-CimInstance -ClassName Win32_BaseBoard).SerialNumber; EnclosureAssetTag = (Get-CimInstance -ClassName Win32_SystemEnclosure).SMBIOSAssetTag} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "CONTROLLERS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "$controllers = @{'Win32_IDEController' = 'IDE'; 'Win32_SCSIController' = 'SCSI'; 'Win32_USBController' = 'USB'; 'Win32_InfraredDevice' = 'Infrared'; 'Win32_1394Controller' = '1394'; 'Win32_PCMCIAController' = 'PCMCIA'}; $controllers.Keys | ForEach-Object { $type = $controllers[$_]; Get-CimInstance -ClassName $_ | ForEach-Object {[PSCustomObject]@{Type = $type; Manufacturer = $_.Manufacturer; Name = $_.Name; Caption = $_.Caption; Description = $_.Description; Version = $_.HardwareVersion}}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "CPUS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-CimInstance -ClassName Win32_Processor | Select-Object *, @{Name = 'ArchitectureDecoded'; Expression = {switch ($_.Architecture) {0 {'x86'}; 1 {'MIPS'}; 2 {'Alpha'}; 3 {'PowerPC'}; 5 {'ARM'}; 6 {'ia64 Itanium'}; 9 {'x64'}; 12 {'ARM64'}}}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "DRIVES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object *, @{Name = 'Type'; Expression = {switch ($_.MediaType) {0 {'Format is unknown'} 1 {'5-Inch Floppy Disk'} 2 {'3-Inch Floppy Disk'} 3 {'3-Inch Floppy Disk'} 4 {'3-Inch Floppy Disk'} 5 {'3-Inch Floppy Disk'} 6 {'5-Inch Floppy Disk'} 7 {'5-Inch Floppy Disk'} 8 {'5-Inch Floppy Disk'} 9 {'5-Inch Floppy Disk'} 10 {'5-Inch Floppy Disk'} 11 {'Removable media other than floppy'} 12 {'Fixed hard disk media'} 13 {'3-Inch Floppy Disk'} 14 {'3-Inch Floppy Disk'} 15 {'5-Inch Floppy Disk'} 16 {'5-Inch Floppy Disk'} 17 {'3-Inch Floppy Disk'} 18 {'3-Inch Floppy Disk'} 19 {'5-Inch Floppy Disk'} 20 {'3-Inch Floppy Disk'} 21 {'3-Inch Floppy Disk'} 22 {'8-Inch Floppy Disk'}}}}, @{Name = 'FreeSpaceMiB'; Expression = {[math]::Round($_.FreeSpace / 1MB, 2)}}, @{Name = 'SizeMiB'; Expression = {[math]::Round($_.Size / 1MB, 2)}}, @{Name = 'UsedPercent'; Expression = {[math]::Round((($_.Size - $_.FreeSpace) / $_.Size) * 100, 2)}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "INPUTS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "@(@{Class = 'Win32_Keyboard'; Type = 'Keyboard'}, @{Class = 'Win32_PointingDevice'; Type = 'Pointing Device'}, @{Class = 'Win32_PnPSignedDriver'; Type = 'PnP Signed Driver'; Filter = \"DeviceClass = 'SMARTCARDREADER'\"}) | ForEach-Object {$class = $_.Class; $type = $_.Type; $filter = $_.Filter; $instances = if ($filter) {Get-CimInstance -ClassName $class -Filter $filter} else {Get-CimInstance -ClassName $class}; $instances | ForEach-Object {[PSCustomObject]@{Type = $type; Manufacturer = $_.Manufacturer; Caption = $_.Caption; Description = $_.Description; Interface = switch ($_.DeviceInterface) {1 {'Other'}; 2 {'Unknown'}; 3 {'Serial'}; 4 {'PS/2'}; 5 {'Infrared'}; 6 {'HP-HIL'}; 7 {'Bus mouse'}; 8 {'ADB (Apple Desktop Bus)'}; 160 {'Bus mouse DB-9'}; 161 {'Bus mouse micro-DIN'}; 162 {'USB'}}}}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "LOCAL GROUPS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": 'Get-CimInstance -ClassName Win32_Group -Filter "LocalAccount = True" | ConvertTo-Json',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "LOCAL USERS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": 'Get-CimInstance -ClassName Win32_UserAccount -Filter "LocalAccount = True" | ConvertTo-Json',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "MEMORIES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-CimInstance -ClassName Win32_PhysicalMemory | ForEach-Object {$memoryArray = Get-CimInstance -ClassName Win32_PhysicalMemoryArray; [PSCustomObject]@{Caption = $_.Caption; BankLabel = $_.BankLabel; CapacityMiB = [math]::Round($_.Capacity / 1MB, 2); Use = switch ($memoryArray.Use) {0 {'Reserved'}; 1 {'Other'}; 2 {'Unknown'}; 3 {'System memory'}; 4 {'Video memory'}; 5 {'Flash memory'}; 6 {'Non-volatile RAM'}; 7 {'Cache memory'}}; MemoryType = switch ($_.MemoryType) {0 {'Unknown'}; 1 {'Other'}; 2 {'DRAM'}; 3 {'Synchronous DRAM'}; 4 {'Cache DRAM'}; 5 {'EDO'}; 6 {'EDRAM'}; 7 {'VRAM'}; 8 {'SRAM'}; 9 {'RAM'}; 10 {'ROM'}; 11 {'Flash'}; 12 {'EEPROM'}; 13 {'FEPROM'}; 14 {'EPROM'}; 15 {'CDRAM'}; 16 {'3DRAM'}; 17 {'SDRAM'}; 18 {'SGRAM'}; 19 {'RDRAM'}; 20 {'DDR'}; 21 {'DDR2'}; 22 {'DDR2 FB-DIMM'}; 24 {'DDR3'}; 25 {'FBD2'}; 26 {'DDR4'}}; Speed = $_.Speed; SlotNumber = $_.DeviceLocator; SerialNumber = $_.SerialNumber}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "MONITORS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": 'Get-CimInstance -Namespace root/wmi -ClassName WmiMonitorID | ForEach-Object {$monitorParams = Get-CimInstance -Namespace root/wmi -ClassName WmiMonitorBasicDisplayParams; [PSCustomObject]@{Manufacturer = [System.Text.Encoding]::ASCII.GetString($_.ManufacturerName).TrimEnd("`0"); InstanceName = $_.InstanceName; ManufacturedOn = "$($_.WeekOfManufacture)/$($_.YearOfManufacture)"; Type = switch ($monitorParams.VideoInputType) {0 {\'Analog\'}; 1 {\'Digital\'}}; SerialNumber = [System.Text.Encoding]::ASCII.GetString($_.SerialNumberID).TrimEnd("`0"); Active = $_.Active}} | ConvertTo-Json',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "NETWORKS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-NetAdapter | ForEach-Object { $adapter = $_; $wmiAdapter = Get-CimInstance -Class Win32_NetworkAdapter | Where-Object { $_.NetConnectionID -eq $adapter.Name }; $config = Get-CimInstance -Class Win32_NetworkAdapterConfiguration | Where-Object { $_.Index -eq $wmiAdapter.DeviceID }; [PSCustomObject]@{ Name = $adapter.Name; Description = $adapter.InterfaceDescription; Type = $adapter.ifAlias; Speed = $adapter.LinkSpeed; MTU = $adapter.MtuSize; MACAddress = $adapter.MacAddress; Status = $adapter.Status; IPAddress = $config.IPAddress; NetMask = $config.IPSubnet; Gateway = $config.DefaultIPGateway; NetworkNumber = if ($config.IPAddress -and $config.IPSubnet) { [System.Net.IPAddress]::new([byte[]](0..3 | ForEach-Object { [System.Net.IPAddress]::Parse($config.IPAddress[0]).GetAddressBytes()[$_] -band [System.Net.IPAddress]::Parse($config.IPSubnet[0]).GetAddressBytes()[$_] })).ToString() } else { $null }; DHCPServer = $config.DHCPServer } } | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "PORTS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "$ports = @{'Win32_PortConnector' = ''; 'Win32_SerialPort' = 'Serial'; 'Win32_ParallelPort' = 'Parallel'}; $ports.Keys | ForEach-Object {$type = $ports[$_]; Get-CimInstance -ClassName $_ | ForEach-Object {[PSCustomObject]@{Type = if ($type) {$type} else {switch ($_.PortType) {0 {'None'}; 1 {'Parallel Port XT/AT Compatible'}; 2 {'Parallel Port PS/2'}; 3 {'Parallel Port ECP'}; 4 {'Parallel Port EPP'}; 5 {'Parallel Port ECP/EPP'}; 6 {'Serial Port XT/AT Compatible'}; 7 {'Serial Port 16450 Compatible'}; 8 {'Serial Port 16550 Compatible'}; 9 {'Serial Port 16550A Compatible'}; 10 {'SCSI Port'}; 11 {'MIDI Port'}; 12 {'Joy Stick Port'}; 13 {'Keyboard Port'}; 14 {'Mouse Port'}; 15 {'SSA SCSI'}; 16 {'USB'}; 17 {'FireWire (IEEE P1394)'}; 18 {'PCMCIA Type II'}; 19 {'PCMCIA Type II'}; 20 {'PCMCIA Type III'}; 21 {'Cardbus'}; 22 {'Access Bus Port'}; 23 {'SCSI II'}; 24 {'SCSI Wide'}; 25 {'PC-98'}; 26 {'PC-98-Hireso'}; 27 {'PC-H98'}; 28 {'Video Port'}; 29 {'Audio Port'}; 30 {'Modem Port'}; 31 {'Network Port'}; 32 {'8251 Compatible'}; 33 {'8251 FIFO Compatible'}}}; Name = if ($_.ExternalReferenceDesignator) {$_.ExternalReferenceDesignator} else {$_.Name}; Caption = $_.Caption; Description = $_.Description}}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "PRINTERS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-CimInstance -ClassName Win32_Printer | Select-Object *, @{Name='Resolution'; Expression = {\"$($_.HorizontalResolution) x $($_.VerticalResolution)\"}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "SLOTS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-CimInstance -ClassName Win32_SystemSlot | Select-Object *, @{Name = 'Purpose'; Expression = {switch ($_.CurrentUsage) {0 {'Reserved'}; 1 {'Other'}; 2 {'Unknown'}; 3 {'Available'}; 4 {'In Use'}}}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "SOFTWARES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-ItemProperty HKLM:\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*, HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\* | Where-Object { $_.DisplayName -and $_.SystemComponent -ne 1 } | Select-Object -Property *, @{Name='LanguageName';Expression={ try { if ($_.Language) { $lcid=[int]$_.Language; (New-Object System.Globalization.CultureInfo $lcid).DisplayName } else { 'Unknown' } } catch { 'Unknown' } }}, @{Name='InstallDateFormatted';Expression={ if ($_.InstallDate -match '^\\d{8}$') { [datetime]::ParseExact($_.InstallDate,'yyyyMMdd',$null).ToString('yyyy/MM/dd') } else { 'Unknown' } }}, @{Name='InstallPath';Expression={ $exe=$null; $c=@($_.DisplayIcon,$_.UninstallString,$_.QuietUninstallString,$_.ModifyPath) | Where-Object { $_ -and $_.ToString().Trim() -ne '' }; foreach($s in $c){ $m=[regex]::Match($s,'(?i)(?:^|[ \\t])\"?(?<exe>(?:[a-z]:|\\\\)[^\",]+?\\.exe)'); if($m.Success){ $p=$m.Groups['exe'].Value.Trim('\"'); $n=[System.IO.Path]::GetFileName($p); if($n -ieq 'msiexec.exe' -or $n -ieq 'rundll32.exe'){ continue }; $exe=$p; break } }; if ($_.InstallLocation) { $_.InstallLocation } elseif ($exe) { [System.IO.Path]::GetDirectoryName($exe) } else { $null } }}, @{Name='ExecutableName';Expression={ $exe=$null; $c=@($_.DisplayIcon,$_.UninstallString,$_.QuietUninstallString,$_.ModifyPath) | Where-Object { $_ -and $_.ToString().Trim() -ne '' }; foreach($s in $c){ $m=[regex]::Match($s,'(?i)(?:^|[ \\t])\"?(?<exe>(?:[a-z]:|\\\\)[^\",]+?\\.exe)'); if($m.Success){ $p=$m.Groups['exe'].Value.Trim('\"'); $n=[System.IO.Path]::GetFileName($p); if($n -ieq 'msiexec.exe' -or $n -ieq 'rundll32.exe'){ continue }; $exe=$p; break } }; if($exe){ [System.IO.Path]::GetFileName($exe) } else { $null } }}, @{Name='VersionPatch';Expression={ if ($_.DisplayVersion) { [regex]::Match((($_.DisplayVersion -split '\\.')[2]), '^\\d+').Value } else { $null } }} -ExcludeProperty PSProvider, PSDrive | ConvertTo-Json -Depth 4",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "SOUNDS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-CimInstance -ClassName Win32_SoundDevice | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "STORAGES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "$storages = @('Win32_DiskDrive', 'Win32_CDROMDrive', 'Win32_TapeDrive'); $storages | ForEach-Object {Get-CimInstance -ClassName $_ | ForEach-Object {[PSCustomObject]@{Manufacturer = $_.Manufacturer; Name = $_.Name; Model = $_.Model; Description = $_.Description; Type = $_.MediaType; Size = [math]::Round($_.Size / 1MB, 2); SerialNumber = $_.SerialNumber; Firmware = if ($_.FirmwareRevision) {$_.FirmwareRevision} else {$_.RevisionLevel}}}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "USB DEVICES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject Win32_PnPEntity | Where-Object { $_.PNPDeviceID -like 'USB*' } | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "VIDEOS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-CimInstance -ClassName Win32_VideoController | Select-Object *, @{Name='AdapterRAMMiB'; Expression = {[math]::Round($_.AdapterRAM / 1MB, 2)}}, @{Name='Resolution'; Expression = {\"$($_.CurrentHorizontalResolution) x $($_.CurrentVerticalResolution)\"}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "VIRTUAL MACHINES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "@() | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "FIREWALL RULES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-NetFirewallRule | ForEach-Object { $p = Get-NetFirewallPortFilter -AssociatedNetFirewallRule $_; $a = Get-NetFirewallAddressFilter -AssociatedNetFirewallRule $_; [PSCustomObject]@{ DisplayName=$_.DisplayName; Source=$a.LocalAddress; Source_Port=$p.LocalPort; Destination=$a.RemoteAddress; Destination_Port=$p.RemotePort; Direction=$_.Direction; Action=$_.Action; Protocol=if($p.Protocol -eq 'Any'){''}elseif($p.Protocol -match '^\\d+$'){@{0='IP';1='ICMP';2='IGMP';6='TCP';17='UDP';41='IPv6';58='ICMPv6'}[[int]$p.Protocol]}else{$p.Protocol}; Comment=$_.Description } } | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "UPTIME",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "$os = Get-CimInstance -ClassName Win32_OperatingSystem; $uptime = [DateTime]::Now - $os.LastBootUpTime; [PSCustomObject]@{ Log_Date = Get-Date $os.LastBootUpTime -Format 'yyyy-MM-dd HH:mm:ss'; Duration = \"$($uptime.Days) days, $($uptime.Hours) hours, $($uptime.Minutes) minutes\" } | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "OS INSTALL",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "$os = Get-WmiObject -Class Win32_OperatingSystem; $reg = Get-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion'; [PSCustomObject]@{ InstallDate=$os.ConvertToDateTime($os.InstallDate).ToString('yyyy-MM-dd HH:mm:ss'); BuildVersion='{0}.{1}' -f $reg.CurrentBuild, $reg.UBR; CodeSet=$os.CodeSet; CountryCode=$os.CountryCode; OSLanguage=$os.OSLanguage; CurrentTimeZone=$os.CurrentTimeZone; Locale=$os.Locale } | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "POWERSHELL VERSION",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": '$v = $PSVersionTable.PSVersion; [PSCustomObject]@{ Version="$($v.Major).$($v.Minor).$($v.Build).$($v.Revision)"; Major=$v.Major; Minor=$v.Minor; Build=$v.Build; Revision=$v.Revision } | ConvertTo-Json',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "DRIVERS LIST",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": 'Get-WmiObject Win32_PnPSignedDriver | Where-Object { $_.DeviceClass -ne $null } | ForEach-Object { [PSCustomObject]@{ Description=$_.Description; Class=$_.DeviceClass; DeviceID=$_.DeviceID; Name=$_.DeviceName; Date=if($_.DriverDate){$_.DriverDate.Substring(0,4)+"/"+$_.DriverDate.Substring(4,2)+"/"+$_.DriverDate.Substring(6,2)}else{"NC"}; ProviderName=$_.DriverProviderName; Version=$_.DriverVersion; FriendlyName=$_.FriendlyName; InfName=$_.InfName; Signed=$_.IsSigned } } | ConvertTo-Json -Depth 5',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "SCHEDULED TASKS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "schtasks /query /FO CSV /v /NH | ForEach-Object { $c = $_ -split '\",\"'; [PSCustomObject]@{ Name=$c[4]; NextExecHour=$c[7]; State=$c[10]; LastExecHour=$c[16]; LastResult=$c[19]; Creator=$c[22]; TaskToExecute=$c[25]; StartIn=$c[28]; Comment=$c[31]; TaskStatus=$c[34]; ExecuteAs=$c[43]; DelTask=$c[46]; StopTaskAfter=$c[49]; Planning=$c[52]; Type=$c[55]; BeginHour=$c[58]; BeginDate=$c[61]; EndDate=$c[64]; Day=$c[67]; Month=$c[70] } } | ConvertTo-Json -Depth 5",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "SECURITY CERTIFICATE",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": 'Get-ChildItem -Recurse cert:\\LocalMachine | Where-Object { $_.FriendlyName -ne $null } | ForEach-Object { [PSCustomObject]@{ Name=if($_.FriendlyName.TrimEnd() -eq ""){$_.Issuer}else{$_.FriendlyName}; Authority=$_.Issuer; DateStart=$_.NotBefore; Expiration=$_.NotAfter } } | ConvertTo-Json -Depth 5',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "SERVICES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-WmiObject Win32_Service | Select-Object Name, DisplayName, State, Description, StartMode, PathName, StartName, ExitCode, ServiceSpecificExitCode | ConvertTo-Json -Depth 5",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "WIN SEC DETAILS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-MpComputerStatus | Select-Object AMEngineVersion, AMProductVersion, AMRunningMode, AMServiceEnabled, AMServiceVersion,     AntispywareEnabled, AntispywareSignatureAge, AntispywareSignatureLastUpdated, AntispywareSignatureVersion,     AntivirusEnabled, AntivirusSignatureAge, AntivirusSignatureLastUpdated, AntivirusSignatureVersion,     BehaviorMonitorEnabled, IoavProtectionEnabled, IsTamperProtected,     NISEnabled, NISEngineVersion, NISSignatureAge, NISSignatureLastUpdated, NISSignatureVersion,     OnAccessProtectionEnabled, RealTimeProtectionEnabled, TamperProtectionSource | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "WMI PRODUCT LIST",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": '$installStates = @{-6="Bad Configuration";-2="Invalid Argument";-1="Unknown Package";1="Advertised";2="Absent";5="Installed"}; $results = Get-WmiObject Win32_Product | Where-Object { $_.Name } | ForEach-Object { [PSCustomObject]@{ Name=$_.Name; Vendor=$_.Vendor; Version=$_.Version; InstallState=if($installStates.ContainsKey([int]$_.InstallState)){$installStates[[int]$_.InstallState]}else{"$($_.InstallState)"}; InstallDate=$_.InstallDate.Insert(4,\'-\').Insert(7,\'-\'); IdentifyingNumber=$_.IdentifyingNumber; HelpLink=$_.HelpLink; InstallSource=$_.InstallSource } }; if ($results) { $results | ConvertTo-Json -Depth 5 } else { "[]" }',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "ANY DESK",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": 'function Read-AnyDeskConf($path) { $s = @{}; if (Test-Path $path) { Get-Content $path | ForEach-Object { if ($_ -match \'^(.+?)=(.*)$\') { $s[$Matches[1].Trim()] = $Matches[2].Trim() } } }; return $s }; $results = @(); $systemConf = "$env:PROGRAMDATA\\AnyDesk\\system.conf"; if (!(Test-Path $systemConf)) { $sub = Get-ChildItem "$env:PROGRAMDATA\\AnyDesk" -Directory -EA SilentlyContinue | Where-Object { Test-Path "$($_.FullName)\\system.conf" } | Select-Object -First 1; if ($sub) { $systemConf = "$($sub.FullName)\\system.conf" } }; $userConf = "$env:APPDATA\\AnyDesk\\system.conf"; foreach ($conf in @(@{File=$systemConf;Source="System"}, @{File=$userConf;Source="User"})) { if (Test-Path $conf.File) { $s = Read-AnyDeskConf $conf.File; $id = $s["ad.anynet.id"]; $ver = $s["ad.anynet.cur_version"]; $alias = $s["ad.anynet.alias"]; if (!$id -and !$ver) { $id = "No data available in table" }; $results += [PSCustomObject]@{ Source=$conf.Source; ADID=$id; Version=$ver; Alias=$alias } } }; if ($results) { $results | ConvertTo-Json -Depth 5 } else { "[]" }',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "BATTERIES",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-CimInstance -ClassName Win32_Battery | ForEach-Object {$battery = $_; $staticData = Get-WmiObject -Namespace root/wmi -ClassName BatteryStaticData | Where-Object {$_.UniqueID -eq $battery.DeviceID}; [PSCustomObject]@{Chemistry = switch ($_.Chemistry) {1 {'Other'}; 2 {'Unknown'}; 3 {'Lead Acid'}; 4 {'Nickel Cadmium'}; 5 {'Nickel Metal Hydride'}; 6 {'Lithium-ion'}; 7 {'Zinc air'}; 8 {'Lithium Polymer'}}; Description = $_.Description; DesignCapacityWh = [math]::Round($_.DesignCapacity / 1000, 2); DesignVoltageV = [math]::Round($_.DesignVoltage / 1000, 2); EstimatedChargeRemaining = $_.EstimatedChargeRemaining; ManufacturerName = $staticData.ManufacturerName; Name = $_.Name; SerialNumber = $staticData.SerialNumber; Status = $_.Status}} | ConvertTo-Json",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "USER INSTALLED APPS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": '$profileList = Get-ItemProperty -Path "Registry::HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\ProfileList\\*" -EA Ignore | Select-Object ProfileImagePath, PSChildName; function Get-Sid($pth, $pl) { ($pl | Where-Object { $_.ProfileImagePath -eq $pth }).PSChildName }; [System.Collections.ArrayList]$users = (Get-ChildItem \'C:\\Users\' | Select-Object -ExpandProperty Name); while ($users -contains "Public") { $users.Remove("Public") }; $results = @(); $appnames = @(); foreach ($user in $users) { $sid = Get-Sid "C:\\Users\\$user" $profileList; $regApps = Get-ItemProperty -Path @("Registry::HKEY_USERS\\$sid\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*","Registry::HKEY_USERS\\$sid\\Software\\","Registry::HKEY_USERS\\$sid\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\*") -EA Ignore; foreach ($app in $regApps) { if ($app) { $appname = $(if ($app.DisplayName) { $app.DisplayName } else { $app.PSChildName }); $appname = $appname -replace "\\.[^.]*$",""; $publisher = $(if ($app.Publisher) { $app.Publisher } else { "" }); $version = $(if ($app.DisplayVersion) { $app.DisplayVersion } else { "" }); if (!(@($appnames) -like "*$appname*")) { $results += [PSCustomObject]@{ UserName=$user; AppName=$appname; Publisher=$publisher; Version=$version }; $appnames += $appname } } } }; Get-ItemProperty -Path "Registry::HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*" -EA Ignore | Where-Object { $_.UninstallString -match "C:\\\\Users\\\\([a-zA-Z0-9_\\-\\s]*)\\\\.*" } | ForEach-Object { $username = $Matches[1]; $appname = $_.DisplayName; $publisher = $(if ($_.Publisher) { $_.Publisher } else { "" }); $version = $(if ($_.DisplayVersion) { $_.DisplayVersion } else { "" }); if (!(@($appnames) -like "*$appname*")) { $results += [PSCustomObject]@{ UserName=$username; AppName=$appname; Publisher=$publisher; Version=$version }; $appnames += $appname } }; if ($results) { $results | ConvertTo-Json -Depth 5 } else { "[]" }',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "FIREWALL CONFIG",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "$lines = (& netsh advfirewall show all) -split '\\r?\\n'; $language = if ($lines[1] -match '^(Domain|Private|Public) Profile Settings:') { 'English' } else { 'French' }; $attrState = if ($language -eq 'French') { 'Ãtat' } else { 'State' }; $attrPolicy = if ($language -eq 'French') { 'StratÃ©gie de pare-feu' } else { 'Firewall Policy' }; $attrParam = if ($language -eq 'French') { 'ParamÃ¨tres' } else { 'Settings' }; $profiles = @(); $current = $null; foreach ($line in $lines) { if ($line -match 'profil') { if ($current) { $profiles += $current }; $current = New-Object PSObject; $current | Add-Member NoteProperty \"Profile\" ($line.Replace(\":\",\"\").Replace($attrParam,\"\").Trim()) } elseif ($line -match '^\\S' -and $current) { $parts = $line -split '\\s{2,}', 2; if ($parts.Count -eq 2) { $current | Add-Member NoteProperty $parts[0].Trim() $parts[1].Trim() } } }; if ($current) { $profiles += $current }; $profiles | ForEach-Object { [PSCustomObject]@{ Profile=$_.Profile; State=$_.$attrState; FirewallPolicy=$_.$attrPolicy; LocalFirewallRules=$_.LocalFirewallRules; FileName=$_.FileName; MaxFileSize=$_.MaxFileSize } } | ConvertTo-Json -Depth 5",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "WIN UPDATE",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": '$offsetMin = [System.TimeZoneInfo]::Local.GetUtcOffset((Get-Date)).TotalMinutes; $searcher = (New-Object -ComObject "Microsoft.Update.Session").CreateUpdateSearcher(); $updates = @(); $results = @(); $searcher.QueryHistory(0, $searcher.GetTotalHistoryCount()) | ForEach-Object { $update = $_; [regex]::match($update.Title,\'(KB[0-9]{6,7})\').value | Where-Object { $_ -ne "" } | ForEach-Object { if ($_ -notin $updates) { $updates += $_ }; $results += [PSCustomObject]@{ Source="UpdateHistory"; KB=$_; Title=$update.Title; Date=$update.Date.AddMinutes($offsetMin).ToString("yyyy-MM-dd HH:mm:ss"); Operation=@{1="Installation";2="Uninstallation";3="Other"}[[int]$update.Operation]; Status=@{1="In progress";2="Succeeded";3="Succeeded with errors";4="Failed";5="Aborted"}[[int]$update.ResultCode]; SupportLink=$update.SupportUrl; Description=$update.Description } } }; Get-HotFix | Where-Object { $updates -notcontains $_.HotFixID } | ForEach-Object { $results += [PSCustomObject]@{ Source="HotFix"; KB=$_.HotFixID; Title="HotFix"; Date=$_.InstalledOn.ToString("yyyy-MM-dd HH:mm:ss"); Operation="Installation"; Status="Succeeded"; SupportLink=""; Description=$_.Description } }; (New-Object -ComObject "Microsoft.Update.AutoUpdate").Results | ForEach-Object { $results += [PSCustomObject]@{ Source="ScanInfo"; KB=""; Title="Last update scan"; Date=$_.LastSearchSuccessDate.ToString("yyyy-MM-dd HH:mm:ss"); Operation=""; Status=""; SupportLink=""; Description="LastInstallationDate: $($_.LastInstallationSuccessDate.ToString(\'yyyy-MM-dd HH:mm:ss\'))" } }; $results | ConvertTo-Json -Depth 5',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "UNIVERSAL WINDOWS PLATFORMS APPS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-AppxPackage -AllUsers | Select-Object Name, Architecture, Version, PackageFullName, Status, Publisher, InstallLocation | ConvertTo-Json -Depth 5",
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "TEAM VIEWER",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": '$regPath = @("HKLM:\\SOFTWARE\\WOW6432Node\\TeamViewer","HKLM:\\SOFTWARE\\TeamViewer") | Where-Object { Test-Path $_ } | Select-Object -Last 1; if ($regPath) { Get-ItemProperty -Path $regPath | ForEach-Object { [PSCustomObject]@{ Version=$_.Version; ClientID=$_.ClientID } } | ConvertTo-Json } else { "{}" }',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "BROWSERS EXTENSIONS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": '$results = @(); foreach ($user in (Get-ChildItem \'C:\\Users\\\').Name) { $chromePaths = @(\'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\',\'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\'); if ($chromePaths | Where-Object { Test-Path $_ }) { $localState = "C:\\Users\\$user\\AppData\\Local\\Google\\Chrome\\User Data\\Local State"; if (Test-Path $localState) { $profileFolder = ((Get-Content $localState -Raw | ConvertFrom-Json).profile.last_active_profiles); if (!$profileFolder) { $profileFolder = \'Default\' }; $extSettings = "C:\\Users\\$user\\AppData\\Local\\Google\\Chrome\\User Data\\$profileFolder\\Local Extension Settings"; if (Test-Path $extSettings) { foreach ($ext in (Get-ChildItem $extSettings)) { $appid = $ext.BaseName; $extPath = "C:\\Users\\$user\\AppData\\Local\\Google\\Chrome\\User Data\\$profileFolder\\Extensions\\$appid"; if (Test-Path $extPath) { foreach ($vFolder in (Get-ChildItem $extPath)) { $name = ""; $manifest = "$($vFolder.FullName)\\manifest.json"; if (Test-Path $manifest) { try { $j = Get-Content -Raw $manifest | ConvertFrom-Json; $name = $j.name } catch { $name = "" } }; if ($name -like "*MSG*") { foreach ($locale in @("en","en_US")) { $msgFile = "$($vFolder.FullName)\\_locales\\$locale\\messages.json"; if (Test-Path $msgFile) { try { $j = Get-Content -Raw $msgFile | ConvertFrom-Json; $name = $j.appName.message; if (!$name) { $name = $j.extName.message }; if (!$name) { $name = $j.extensionName.message }; if (!$name) { $name = $j.app_name.message }; if (!$name) { $name = $j.application_title.message } } catch { $name = "" } } } }; if (!$name) { $name = "[$appid]" }; $results += [PSCustomObject]@{ UserName=$user; BrowserName="Chrome"; ExtensionName=$name; ExtensionVersion=$vFolder.Name; ExtensionID=$appid } } } } } }; $edgePath = "C:\\Users\\$user\\AppData\\Local\\Microsoft\\Edge\\User Data"; if (Test-Path $edgePath) { $edgeProfileFolder = "Default"; $edgeLocalState = "$edgePath\\Local State"; if (Test-Path $edgeLocalState) { $ep = ((Get-Content $edgeLocalState -Raw | ConvertFrom-Json).profile.last_active_profiles); if ($ep) { $edgeProfileFolder = $ep } }; $edgeExtSettings = "$edgePath\\$edgeProfileFolder\\Local Extension Settings"; if (Test-Path $edgeExtSettings) { foreach ($ext in (Get-ChildItem $edgeExtSettings)) { $appid = $ext.BaseName; $extPath = "$edgePath\\$edgeProfileFolder\\Extensions\\$appid"; if (Test-Path $extPath) { foreach ($vFolder in (Get-ChildItem $extPath)) { $name = ""; $manifest = "$($vFolder.FullName)\\manifest.json"; if (Test-Path $manifest) { try { $j = Get-Content -Raw $manifest | ConvertFrom-Json; $name = $j.name } catch { $name = "" } }; if ($name -like "*MSG*") { foreach ($locale in @("en","en_US")) { $msgFile = "$($vFolder.FullName)\\_locales\\$locale\\messages.json"; if (Test-Path $msgFile) { try { $j = Get-Content -Raw $msgFile | ConvertFrom-Json; $name = $j.appName.message; if (!$name) { $name = $j.extName.message }; if (!$name) { $name = $j.extensionName.message }; if (!$name) { $name = $j.app_name.message }; if (!$name) { $name = $j.application_title.message } } catch { $name = "" } } } }; if (!$name) { $name = "[$appid]" }; $results += [PSCustomObject]@{ UserName=$user; BrowserName="Edge"; ExtensionName=$name; ExtensionVersion=$vFolder.Name; ExtensionID=$appid } } } } } }; $ffPaths = @(\'C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe\',\'C:\\Program Files\\Mozilla Firefox\\firefox.exe\'); if ($ffPaths | Where-Object { Test-Path $_ }) { $ffdir = "C:\\Users\\$user\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles"; if (Test-Path $ffdir) { foreach ($ejson in (Get-ChildItem $ffdir -Filter "extensions.json" -Recurse -File)) { foreach ($addon in ((Get-Content $ejson.FullName -Raw | ConvertFrom-Json).addons | Where-Object { $_.location -ne "app-builtin" -and $_.location -ne "app-system-defaults" })) { $results += [PSCustomObject]@{ UserName=$user; BrowserName="Firefox"; ExtensionName=$addon.defaultlocale.name; ExtensionVersion=$addon.version; ExtensionID=$addon.id } } } } } }; if ($results) { $results | ConvertTo-Json -Depth 5 } else { "[]" }',
            "options": {"submap": None},
            "template": template,
        },
        {
            "name": "BITLOCKER STATUS",
            "retrieval_method": "PW",
            "retrieval_output": "JSON",
            "target": "Get-BitLockerVolume | ForEach-Object { [PSCustomObject]@{ Drive=$_.MountPoint; VolumeType=$_.VolumeType; ConversionStatus=$_.VolumeStatus; ProtectionStatus=$_.ProtectionStatus; EncryptionMethod=$_.EncryptionMethod; InitProtect=$_.IsVolumeInitializedForProtection } } | ConvertTo-Json -Depth 5",
            "options": {"submap": None},
            "template": template,
        },
    ]

    for section in sections:
        try:
            Section.objects.create(**section)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0010_legacy_extended"),
        ("template", "0004_windows_extended"),
    ]

    operations = [
        migrations.RunPython(create_windows_extended_sections),
    ]
