# Generated by Django 6.0.8 on 2026-08-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0013_linux_extended_rhel"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
