# Generated by Django 3.2 on 2021-06-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
        ('base', '0002_alter_base_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='template.template'),
            preserve_default=False,
        ),
    ]
