# Generated by Django 3.2 on 2021-06-01 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0001_initial"),
        ("base", "0003_base_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="base",
            name="template",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="template.template",
            ),
        ),
    ]
