# Generated by Django 3.2 on 2021-06-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
        ('base', '0004_alter_base_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='template.template'),
        ),
    ]
