# Generated by Django 4.2.3 on 2024-01-15 09:39

from django.db import migrations, models


def create_admin_user(apps, schema_editor):
    """
    Create admin user with username: admin, password: admin
    """
    User = apps.get_model('auth', 'User')
    user = User.objects.create_superuser('admin', 'admin@localhost', 'admin')
    user.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user)
    ]
