# Generated by Django 4.2.3 on 2024-01-15 09:39

from django.db import migrations


def create_admin_user(apps, schema_editor):
    """
    Create admin user with username: admin, password: admin
    """
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    user = User.objects.create_superuser("admin", "admin@localhost", "admin")
    user.save()

    group = Group.objects.get(name="super-admin")
    user.groups.add(group)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_config", "0001_initial"),
        ("group", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_admin_user)]
