# Generated by Django 4.2.3 on 2024-01-15 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_admin_user(apps, schema_editor):
    """
    Create admin user with username: admin, password: admin
    """
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")
    UserGroupAssignment = apps.get_model("user", "UserGroupAssignment")

    user = User.objects.create_superuser("admin", "admin@localhost", "admin")
    user.save()

    group = Group.objects.get(name="super-admin")
    user.groups.add(group)
    UserGroupAssignment.objects.get_or_create(
        user_id=user.id,
        group_id=group.id,
        source="manual",
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("group", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGroupAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("ldap", "LDAP"),
                            ("rule", "Rule"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_group_assignments",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "source"],
                        name="idx_assignment_user_source",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usergroupassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "group", "source"),
                name="uniq_user_group_source_assignment",
            ),
        ),
        migrations.RunPython(create_admin_user, migrations.RunPython.noop),
    ]
