# Generated by Django 6.0.6 on 2026-06-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(choices=[('INVENTORY_BASE_INSERT', 'Inserting new items into the base inventory'), ('INVENTORY_BASE_UPDATE', 'Updating existing items in the base inventory'), ('INVENTORY_EXT_INSERT', 'Inserting new items into the extended inventory'), ('INVENTORY_EXT_UPDATE', 'Updating existing items in the extended inventory'), ('INVENTORY_BASE_ERR', 'Error related to the base inventory operations'), ('INVENTORY_EXT_ERR', 'Error related to the extended inventory operations'), ('DEPLOYMENT_ACK', 'Acknowledgment of a successful deployment'), ('DEPLOYMENT_ERR', 'Error during the deployment process'), ('CONFIG_UPDATE', 'Updating configuration settings'), ('CONFIG_ERR', 'Error related to configuration operations'), ('TEMPLATE_UPDATE', 'Updating templates for a process'), ('TEMPLATE_ERR', 'Error related to template operations'), ('UNKNOWN', 'Unknown error happend (default)')], default='UNKNOWN', max_length=30)),
                ('comment', models.TextField(max_length=255)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory_base.inventorybase')),
            ],
        ),
    ]
