# Generated by Django 4.2.3 on 2024-01-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_method", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Default Config Name", max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField()),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "auth_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="auth_method.authmethod",
                    ),
                ),
            ],
        ),
    ]
