# Generated by Django 4.2.7 on 2025-04-03 07:32

from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    Section = apps.get_model("section", "Section")
    Category = apps.get_model("category", "Category")

    categories = [
        {
            "name": "Administrative data",
            "description": "Default tab for asset details",
            "is_protected": True,
            "inventory_sections": [
                "ACCOUNTINFO",
                "LOCAL_USERS",
                "LOCAL USERS",
                "LOCAL_GROUPS",
                "LOCAL GROUPS",
            ],
        },
        {
            "name": "Deployment",
            "description": "Default tab for asset deployment",
            "is_protected": True,
        },
        {
            "name": "Hardware",
            "description": "Default tab for hardware sections",
            "is_protected": True,
            "inventory_sections": [
                "BATTERIES",
                "BIOS",
                "CONTROLLERS",
                "CPUS",
                "DRIVES",
                "HARDWARE",
                "MEMORIES",
                "PORTS",
                "SLOTS",
                "SOUNDS",
                "STORAGES",
                "VIDEOS",
            ],
        },
        {
            "name": "Networks",
            "description": "Default tab for network sections",
            "is_protected": True,
            "inventory_sections": ["NETWORKS"],
        },
        {
            "name": "Devices",
            "description": "Default tab for device sections",
            "is_protected": True,
            "inventory_sections": [
                "MONITORS",
                "INPUTS",
                "USBDEVICES",
                "USB DEVICES",
                "PRINTERS",
                "MODEMS",
            ],
        },
        {
            "name": "Softwares",
            "description": "Default tab for software sections",
            "is_protected": True,
            "inventory_sections": ["SOFTWARES"],
        },
        {
            "name": "Others",
            "description": "Default tab for inventory sections",
            "is_protected": True,
            "inventory_sections": [
                "VIRTUALMACHINES",
                "VIRTUAL MACHINES",
                "REPOSITORY",
            ],
        },
    ]

    for category in categories:
        try:
            # Create categories without sections
            obj, created = Category.objects.get_or_create(
                name=category["name"],
                defaults={
                    "description": category["description"],
                    "is_protected": category["is_protected"],
                },
            )

            if created:
                # Set default sections to category after creation
                inventory_sections = Section.objects.filter(
                    name__in=category["inventory_sections"]
                )
                obj.inventory_sections.set(inventory_sections)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("section", "0005_windows"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                (
                    "inventory_sections",
                    models.ManyToManyField(blank=True, to="section.section"),
                ),
                ("is_protected", models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_default_categories),
    ]
