# Generated by Django 4.2.7 on 2025-04-03 07:32

from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    Section = apps.get_model("section", "Section")
    Category = apps.get_model("category", "Category")

    categories = [
        {
            "name": "Administrative data",
            "description": "Default tab for asset details",
            "sections": [
                "ACCOUNT_INFO",
                "USERS",
                "CURRENT_USER",
                "GROUPS",
                "OPERATING_SYSTEM",
            ],
        },
        {
            "name": "Deployment",
            "description": "Default tab for asset deployment",
            "sections": ["DOWNLOADS"],
        },
        {
            "name": "Hardware",
            "description": "Default tab for hardware sections",
            "sections": [
                "BIOS",
                "CPUS",
                "MEMORIES",
                "STORAGES",
                "DRIVES",
                "VIDEOS",
                "SOUNDS",
                "CONTROLLERS",
                "SLOTS",
                "PORTS",
                "BATTERIES",
                "AUDIO",
                "FRAMEWORKS",
                "NVME",
            ],
        },
        {
            "name": "Networks",
            "description": "Default tab for network sections",
            "sections": ["NETWORKS", "ETHERNET", "WI_FI"],
        },
        {
            "name": "Devices",
            "description": "Default tab for device sections",
            "sections": ["INPUTS", "USB", "GRAPHIC/DISPLAY", "BLUETOOTH", "CAMERAS"],
        },
        {
            "name": "Softwares",
            "description": "Default tab for software sections",
            "sections": ["SOFTWARES", "DEVELOPER_TOOLS", "EXTENSIONS"],
        },
        {
            "name": "Others",
            "description": "Default tab for inventory sections",
            "sections": [
                "VIRTUALMACHINES",
                "REPOSITORIES",
                "LOCAL_USERS",
                "LOCAL_GROUPS",
                "TEAMVIEWER",
                "PACKAGES",
            ],
        },
    ]

    for category in categories:
        try:
            # Create categories without sections
            obj, created = Category.objects.get_or_create(
                name=category["name"],
                defaults={"description": category["description"]},
            )

            if created:
                # Set default sections to category after creation
                sections = Section.objects.filter(name__in=category["sections"])
                obj.sections.set(sections)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("section", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("sections", models.ManyToManyField(blank=True, to="section.section")),
            ],
        ),
        migrations.RunPython(create_default_categories),
    ]
