# Generated by Django 4.2.7 on 2025-04-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
