---
name: Issue Message

on:
  issues:
    types: 
      - opened

jobs:
  chatmsg:
    runs-on: ubuntu-latest
    name: Issue chat message
    steps:
      - uses: actions/checkout@v3
      - uses: daniL16/action-notify-rocketChat@2.0.1
        with:
          message: ${{ github.event.issue.html_url }}
          ROCKET_CHAT_HOOK: ${{ secrets.ROCKET_CHAT_ISSUE_HOOK }}
          ROCKET_CHAT_URL: ${{ secrets.ROCKET_CHAT_URL }}
          BOT_NAME: ${{ secrets.ROCKET_CHAT_BOT_NAME }}
