---
name: Pull Request Message

on:
  pull_request:
    types: 
      - opened

jobs:
  chatmsg:
    runs-on: ubuntu-latest
    name: PR chat message
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          message: ${{ github.event.pull_request.html_url }}
          ROCKET_CHAT_HOOK: ${{ secrets.ROCKET_CHAT_PR_HOOK }}
          ROCKET_CHAT_URL: ${{ secrets.ROCKET_CHAT_URL }}
          BOT_NAME: ${{ secrets.ROCKET_CHAT_BOT_NAME }}
