# Generated by Django 4.2.7 on 2025-04-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_section', '0001_initial'),
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inventory_section.inventorysection')),
                ('template_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
            ],
        ),
    ]
