# Generated by Django 6.0.6 on 2026-06-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("field", "0009_alter_field_options_alter_field_retrieval_value_and_more"),
        ("inventory_field", "0001_initial"),
        ("inventory_section", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryfield",
            name="inventory_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="inventory_section.inventorysection",
            ),
        ),
        migrations.AddField(
            model_name="inventoryfield",
            name="template_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="field.field"
            ),
        ),
    ]
